---
title: "Filter observations"
output:
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
description: >
  Learn how to filter observations in a data frame. Use `filter()` to extract
  observations from a data frame, and use `&`, `|`, and `!` to write logical
  tests.
---

```{r setup, include=FALSE}
library(learnr)
library(tidyverse)
library(nycflights13)
library(Lahman)

tutorial_options(
  exercise.timelimit = 60,
  # A simple checker function that just returns the message in the check chunk
  exercise.checker = function(check_code, ...) {
    list(
      message = eval(parse(text = check_code)),
      correct = logical(0),
      type = "info",
      location = "append"
    )
  }
)
knitr::opts_chunk$set(error = TRUE)
```



## Analysing the association of weight and the price of cars 

Before we start, we need to ensure that all necessary libraries are installed and loaded. We use the pacman package for convenient package management.

```{r filter1, exercise = TRUE, exercise.eval = FALSE}
# Install and load required libraries
# Installs 'pacman' if not already available, which is used for package management
if (!require(pacman)) install.packages("pacman")
  
# Unload all previously loaded packages to start fresh
suppressMessages(pacman::p_unload(all))
  
# Load necessary packages for data manipulation, cleaning, and visualization
pacman::p_load(
  tidyverse, # A suite of packages designed for data science that includes tools for data manipulation, plotting, and more.
  haven,     # Used for importing and exporting data with SPSS, Stata, and SAS formats.
  janitor,   # Provides functions for examining and cleaning data, such as `clean_names()` and `tabyl()`.
  WDI,       # Facilitates downloading data from the World Bank's World Development Indicators database.
  wbstats    # Provides an interface to the World Bank's APIs for a comprehensive range of data sets.
)
```
