<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Quantitative Methods - 5&nbsp; Regression analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./experiments.html" rel="next">
<link href="./statistics.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./regression.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regression analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Quantitative Methods</a> 
        <div class="sidebar-tools-main">
    <a href="./Quantitative-Methods.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Preface</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./doing_research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Doing research</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./identification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Identification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regression analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experiments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./publish.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Good research</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exams.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Past exams</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example_questions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Exam(ple) questions</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link active" data-scroll-target="#simple-linear-regression"><span class="header-section-number">5.1</span> Simple linear regression</a>
  <ul class="collapse">
  <li><a href="#estimating-the-coefficients-of-the-linear-regression-model" id="toc-estimating-the-coefficients-of-the-linear-regression-model" class="nav-link" data-scroll-target="#estimating-the-coefficients-of-the-linear-regression-model"><span class="header-section-number">5.1.1</span> Estimating the coefficients of the linear regression model</a></li>
  <li><a href="#the-least-squares-assumptions" id="toc-the-least-squares-assumptions" class="nav-link" data-scroll-target="#the-least-squares-assumptions"><span class="header-section-number">5.1.2</span> The least squares assumptions</a></li>
  <li><a href="#measures-of-fit" id="toc-measures-of-fit" class="nav-link" data-scroll-target="#measures-of-fit"><span class="header-section-number">5.1.3</span> Measures of fit</a></li>
  </ul></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression"><span class="header-section-number">5.2</span> Multiple linear regression</a>
  <ul class="collapse">
  <li><a href="#simpsons-paradox" id="toc-simpsons-paradox" class="nav-link" data-scroll-target="#simpsons-paradox"><span class="header-section-number">5.2.1</span> Simpson’s paradox</a></li>
  <li><a href="#gauss-markov-and-the-best-linear-unbiased-estimator" id="toc-gauss-markov-and-the-best-linear-unbiased-estimator" class="nav-link" data-scroll-target="#gauss-markov-and-the-best-linear-unbiased-estimator"><span class="header-section-number">5.2.2</span> Gauss-Markov and the best linear unbiased estimator</a></li>
  </ul></li>
  <li><a href="#how-to-identify-statistically-significant-estimated-coefficients-in-a-regression-analysis" id="toc-how-to-identify-statistically-significant-estimated-coefficients-in-a-regression-analysis" class="nav-link" data-scroll-target="#how-to-identify-statistically-significant-estimated-coefficients-in-a-regression-analysis"><span class="header-section-number">5.3</span> How to identify statistically significant estimated coefficients in a regression analysis</a>
  <ul class="collapse">
  <li><a href="#p-values" id="toc-p-values" class="nav-link" data-scroll-target="#p-values"><span class="header-section-number">5.3.1</span> P-values</a></li>
  <li><a href="#t-values" id="toc-t-values" class="nav-link" data-scroll-target="#t-values"><span class="header-section-number">5.3.2</span> t-values</a></li>
  <li><a href="#standard-error" id="toc-standard-error" class="nav-link" data-scroll-target="#standard-error"><span class="header-section-number">5.3.3</span> Standard Error</a></li>
  <li><a href="#omitted-variable-bias-and-ceteris-paribus" id="toc-omitted-variable-bias-and-ceteris-paribus" class="nav-link" data-scroll-target="#omitted-variable-bias-and-ceteris-paribus"><span class="header-section-number">5.3.4</span> Omitted variable bias and ceteris paribus</a></li>
  </ul></li>
  <li><a href="#difference-in-difference" id="toc-difference-in-difference" class="nav-link" data-scroll-target="#difference-in-difference"><span class="header-section-number">5.4</span> Difference in difference</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-regression" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regression analysis</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="simple-linear-regression" class="level2 page-columns page-full" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="simple-linear-regression"><span class="header-section-number">5.1</span> Simple linear regression</h2>
<p>The linear regression analysis is a widely used technique for predictive modeling. Its purpose is to establish a mathematical equation that relates a continuous response variable, denoted as <span class="math inline">\(y\)</span>, to one or more independent variables, represented by <span class="math inline">\(x\)</span>. The objective is to create a regression model that enables the prediction of the value of <span class="math inline">\(y\)</span> based on known values of <span class="math inline">\(x\)</span>.</p>
<p>To ensure meaningful predictions, it is important to have an adequate number of observations, denoted as <span class="math inline">\(i\)</span>, available for the variables of interest.</p>
<p>The linear regression model can be expressed as: <span class="math display">\[
y_i = \beta_{0} + \beta_{1} x_i + \epsilon_i,
\]</span> where the index <span class="math inline">\(i\)</span> denotes the individual observations, ranging from <span class="math inline">\(i = 1\)</span> to <span class="math inline">\(n\)</span>. The variable <span class="math inline">\(y_i\)</span> represents the dependent variable, also known as the regressand. The variable <span class="math inline">\(x_i\)</span> represents the independent variable, also referred to as the regressor. <span class="math inline">\(\beta_0\)</span> denotes the intercept of the population regression line, a.k.a. the constant. <span class="math inline">\(\beta_1\)</span> denotes the slope of the population regression line. Lastly, <span class="math inline">\(\epsilon_i\)</span> refers to the error term or the residual, which accounts for the deviation between the predicted and observed values of <span class="math inline">\(y_i\)</span>.</p>
<p>By fitting a linear regression model, one aims to estimate the values of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> in order to obtain an equation that best captures the relationship between <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span>.</p>
<p>While the correlation coefficient and the slope in simple linear regression are similar in many ways, it’s important to note that they are not identical. The correlation coefficient measures the strength and direction of the linear relationship between variables in a broader sense, while the slope in simple linear regression specifically quantifies the change in the dependent variable associated with a unit change in the independent variable.</p>
<section id="estimating-the-coefficients-of-the-linear-regression-model" class="level3 page-columns page-full" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="estimating-the-coefficients-of-the-linear-regression-model"><span class="header-section-number">5.1.1</span> Estimating the coefficients of the linear regression model</h3>
<p>In practice, the intercept and slope of the regression are unknown. Therefore, we must employ data to estimate the unknown parameters, <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. The method we use is called the ordinary least squared (OLS) method. The idea is to minimize the sum of the squared differences of all <span class="math inline">\(y_i\)</span> and <span class="math inline">\(y_i^*\)</span> as sketched in figure <a href="#fig-regressionols" class="quarto-xref">Figure&nbsp;<span>5.1</span></a>.</p>
<div id="fig-regressionols" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-regressionols-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: The fitted line and the residuals
</figcaption>
<div aria-describedby="fig-regressionols-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/regression_ols.png" class="img-fluid figure-img" style="width:50.0%">
</div>
</figure>
</div>
<p>Thus, we minimize the squared residuals by choosing the estimated coefficients <span class="math inline">\(\hat{\beta_{0}}\)</span> and <span class="math inline">\(\hat{\beta_{1}}\)</span> <span class="math display">\[\begin{align*}
   \min_{\hat{\beta_{0}}, \hat{\beta_{1}}}\sum_{i=1} \epsilon_i^2 &amp;= \sum_{i=1} \left[y_i -   \underbrace{(\hat{\beta_{0}} + \hat{\beta_{1}} x_i)}_{\textnormal{predicted values}\equiv y_i^*}\right]^2\\
   \Leftrightarrow  &amp;=  \sum_{i=1}  (y_i - \hat{\beta_{0}} - \hat{\beta_{1}} x_i)^2
\end{align*}\]</span> Minimizing the function requires to calculate the first order conditions with respect to alpha and beta and set them zero: <span class="math display">\[\begin{align*}
   \frac{\partial \sum_{i=1} \epsilon_i^2}{\partial \beta_{0}}=2 \sum_{i=1} (y_i - \hat{\beta_{0}} - \hat{\beta_{1}} x_i)=0\\
   \frac{\partial \sum_{i=1} \epsilon_i^2}{\partial \beta_{1}}=2 \sum_{i=1} (y_i - \hat{\beta_{0}} - \hat{\beta_{1}} x_i)x_i=0
\end{align*}\]</span> This is just a linear system of two equations with two unknowns <span class="math inline">\(\beta_{0}\)</span> and <span class="math inline">\(\beta_{1}\)</span>, which we can mathematically solve for <span class="math inline">\(\beta_0\)</span>: <span class="math display">\[\begin{align*}
   &amp;\sum_{i=1}  (y_i - \hat{\beta_{0}} - \hat{\beta_{1}} x_i)=0\\
   \Leftrightarrow \hat{\beta_{0}}&amp;=\frac{1}{n}\sum_{i=1}   (y_i  - \hat{\beta_{1}} x_i)\\
   \Leftrightarrow \hat{\beta_{0}}&amp;=\bar{y}-\hat{\beta_{1}}\bar{x}
\end{align*}\]</span> and for <span class="math inline">\(\beta_{1}\)</span>: <span class="math display">\[\begin{align*}
   &amp;\sum_{i=1}  (y_i - \hat{\beta_{0}} - \hat{\beta_{1}} x_i)x_i=0\\
   \Leftrightarrow &amp; \sum_{i=1} y_i x_i- \underbrace{\hat{\beta_{0}}}_{\bar{y}-\hat{\beta_{1}}\bar{x}}x_i - \hat{\beta_{1}} x_i^2=0\\
   \Leftrightarrow &amp; \sum_{i=1} y_i x_i- (\bar{y}-\hat{\beta_{1}}\bar{x})x_i - \hat{\beta_{1}} x_i^2=0\\    
   \Leftrightarrow &amp; \sum_{i=1} y_i x_i- \bar{y}x_i-\hat{\beta_{1}}\bar{x}x_i - \hat{\beta_{1}} x_i^2=0\\   
   \Leftrightarrow &amp; \sum_{i=1} (y_i - \bar{y}-\hat{\beta_{1}}\bar{x} - \hat{\beta_{1}} x_i)x_i=0\\
   %    \Leftrightarrow &amp; \sum_{i=1}    (y_i - \bar{y})-\beta_{1}\bar{x} - \hat{\beta_{1}} x_i=0\\
   \Leftrightarrow &amp; \sum_{i=1} (y_i - \bar{y}) x_i -\hat{\beta_{1}}(\bar{x} -  x_i)x_i =0\\
   \Leftrightarrow &amp; \sum_{i=1} (y_i - \bar{y}) x_i  =  \hat{\beta_{1}} \sum_{i=1} (\bar{x} -  x_i) x_i \\
   %    \Leftrightarrow &amp; \beta_{1} =\frac{\sum_{i=1}(y_i - \bar{y})x_i }{ \sum_{i=1} (\bar{x} -  x_i)x_i }\\
   \Leftrightarrow &amp; \hat{\beta_{1}} =\frac{\sum_{i=1}(y_i - \bar{y})x_i }{ \sum_{i=1} (\bar{x} -  x_i)x_i }\\
   \Leftrightarrow &amp; \hat{\beta_{1}} =\frac{\sum_{i=1}(y_i -\bar{y})(x_i-\bar{x})}{\sum_{i=1} (\bar{x} -  x_i)^2 }\\
   \Leftrightarrow &amp; \hat{\beta_{1}} ={\frac {\sigma_{x,y}}{\sigma^2_{x}}}
\end{align*}\]</span> The estimated regression coefficient <span class="math inline">\(\hat{\beta_{1}}\)</span> equals the covariance between <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span> divided by the variance of <span class="math inline">\(x\)</span>.</p>
<p>The formulas presented above may not be very intuitive at first glance. The online version of the book <span class="citation" data-cites="Hanck2020Introduction">Hanck et al. (<a href="references.html#ref-Hanck2020Introduction" role="doc-biblioref">2020</a>)</span> offers a nice interactive application in the box <a href="https://www.econometrics-with-r.org/4.2-estimating-the-coefficients-of-the-linear-regression-model.html">The OLS Estimator, Predicted Values, and Residuals</a> that helps to understand the mechanics of OLS. You can add observations by clicking into the coordinate system where the data are represented by points. Once two or more observations are available, the application computes a regression line using OLS and some statistics which are displayed in the right panel. The results are updated as you add further observations to the left panel. A double-click resets the application, that means, all data are removed.</p>
<div class="no-row-height column-margin column-container"><div id="ref-Hanck2020Introduction" class="csl-entry" role="listitem">
Hanck, C., Arnold, M., Gerber, A., &amp; Schmelzer, M. (2020). <em>Introduction to econometrics with <span>R</span></em>. University of Duisburg-Essen. <a href="https://www.econometrics-with-r.org">www.econometrics-with-r.org</a>
</div></div></section>
<section id="the-least-squares-assumptions" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="the-least-squares-assumptions"><span class="header-section-number">5.1.2</span> The least squares assumptions</h3>
<p>OLS performs well under a quite broad variety of different circumstances. However, there are some assumptions which need to be satisfied in order to ensure that the estimates are normally distributed in large samples.</p>
<p>The Least Squares Assumptions should fulfill the following assumptions: <span class="math display">\[
Y_i = \beta_0 + \beta_1 X_i + \epsilon_i \text{, } i = 1,\dots,n
\]</span></p>
<ul>
<li>The error term <span class="math inline">\(\epsilon_i\)</span> has conditional mean zero given <span class="math inline">\(X_i: E(u_i|X_i)=0\)</span>.</li>
<li><span class="math inline">\((X_i,Y_i), i=1,\dots,n\)</span> are independent and identically distributed (i.i.d.) draws from their joint distribution.</li>
<li>Large outliers are unlikely: <span class="math inline">\(X_i\)</span> and <span class="math inline">\(Y_i\)</span> have nonzero finite fourth moments. That means, assumption 3 requires that <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> have a finite kurtosis.</li>
</ul>
</section>
<section id="measures-of-fit" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="measures-of-fit"><span class="header-section-number">5.1.3</span> Measures of fit</h3>
<p>After fitting a linear regression model, a natural question is how well the model describes the data. Visually, this amounts to assessing whether the observations are tightly clustered around the regression line. Both the coefficient of determination and the standard error of the regression measure how well the OLS Regression line fits the data.</p>
<p><span class="math inline">\(R^2\)</span> is the fraction of the sample variance of <span class="math inline">\(Y_i\)</span> that is explained by <span class="math inline">\(X_i\)</span>. Mathematically, the <span class="math inline">\(R^2\)</span> can be written as the ratio of the explained sum of squares to the total sum of squares. The explained sum of squares (ESS) is the sum of squared deviations of the predicted values <span class="math inline">\(\hat{Y_i}\)</span>, from the average of the <span class="math inline">\(Y_i\)</span>. The total sum of squares (TSS) is the sum of squared deviations of the <span class="math inline">\(Y_i\)</span> from their average. Thus we have <span class="math display">\[\begin{align}
   ESS &amp; =  \sum_{i = 1}^n \left( \hat{Y_i} - \overline{Y} \right)^2,   \\
   TSS &amp; =  \sum_{i = 1}^n \left( Y_i - \overline{Y} \right)^2,   \\
   R^2 &amp; = \frac{ESS}{TSS}.
\end{align}\]</span> Since <span class="math inline">\(TSS = ESS + SSR\)</span> we can also write <span class="math display">\[
R^2 = 1- \frac{\textcolor{blue}{SSR}}{\textcolor{red}{TSS}}
\]</span> with <span class="math display">\[
SSR= \sum_{i = 1}^n \epsilon^2.
\]</span></p>
<div id="fig-fitR" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-fitR-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: Total sum of squares and sum of squared residuals
</figcaption>
<div aria-describedby="fig-fitR-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/fitR.png" class="img-fluid figure-img" style="width:75.0%">
</div>
</figure>
</div>
<p><span class="math inline">\(R^2\)</span> lies between 0 and 1. It is easy to see that a perfect fit, i.e., no errors made when fitting the regression line, implies <span class="math inline">\(R2=1\)</span> since then we have <span class="math inline">\(SSR=0\)</span>. On the contrary, if our estimated regression line does not explain any variation in the <span class="math inline">\(Y_i\)</span>, we have <span class="math inline">\(ESS=0\)</span> and consequently <span class="math inline">\(R^2=0\)</span>. <a href="#fig-fitR" class="quarto-xref">Figure&nbsp;<span>5.2</span></a> represents the relationship of TTS and SSR.</p>
</section>
</section>
<section id="multiple-linear-regression" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="multiple-linear-regression"><span class="header-section-number">5.2</span> Multiple linear regression</h2>
<p>Having understood the simple linear regression model, it is important to broaden our scope beyond the relationship between just two variables: the dependent variable and a single regressor. Our goal is to causally interpret the measured association of two variables, which requires certain conditions as explained in <a href="identification.html" class="quarto-xref"><span>Chapter 3</span></a>.</p>
<section id="simpsons-paradox" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="simpsons-paradox"><span class="header-section-number">5.2.1</span> Simpson’s paradox</h3>
<p>To illustrate this concept, let’s revisit the phenomenon known as Simpson’s paradox. Simpson’s paradox occurs when the overall association between two categorical variables differs from the association observed when we consider the influence of one or more other variables, known as controlling variables. This paradox highlights three key points:</p>
<ol type="1">
<li><p>It challenges the assumption that statistical relationships are fixed and unchanging, showing that the relationship between two variables can vary depending on the set of variables being controlled.</p></li>
<li><p>Simpson’s paradox is part of a larger class of association paradoxes, indicating that similar situations can arise in various contexts.</p></li>
<li><p>It serves as a reminder of the potential pitfalls of making causal inferences in nonexperimental studies, emphasizing the importance of considering confounding variables.</p></li>
</ol>
<p>Thus, it is important to consider confounding variables to ensure valid and reliable causal interpretations in research, particularly in nonexperimental settings.</p>
<div id="fig-foo13" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-foo13-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.3: Simpsons paradox and the power of controlling variables (1)
</figcaption>
<div aria-describedby="fig-foo13-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/foo-13.png" class="img-fluid figure-img" style="width:75.0%">
</div>
</figure>
</div>
<div id="fig-foo32" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-foo32-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.4: Simpsons paradox and the power of controlling variables (2)
</figcaption>
<div aria-describedby="fig-foo32-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/foo-32.png" class="img-fluid figure-img" style="width:75.0%">
</div>
</figure>
</div>
<p>The multiple regression model can be expressed as:</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 X_{1i} + \beta_2 X_{2i} + \beta_3 X_{3i} + \dots + \beta_k X_{ki} + u_i, \ i=1,\dots,n.
\]</span></p>
<p>To estimate the coefficients of the multiple regression model, we seek to minimize the sum of squared mistakes by choosing estimated coefficients <span class="math inline">\(\beta_0,\beta_1,\dots,\beta_k\)</span> such that:</p>
<p><span class="math display">\[
\sum_{i=1}^n (Y_i - b_0 - b_1 X_{1i} - b_2 X_{2i} - \dots -  b_k X_{ki})^2
\]</span></p>
<p>This demands matrix notation which goes beyond the scope of this introduction.</p>
</section>
<section id="gauss-markov-and-the-best-linear-unbiased-estimator" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="gauss-markov-and-the-best-linear-unbiased-estimator"><span class="header-section-number">5.2.2</span> Gauss-Markov and the best linear unbiased estimator</h3>
<p>The Gauss-Markov assumptions, also known as the classical linear regression assumptions, are a set of assumptions that underlie the ordinary least squares (OLS) method for estimating the parameters in a linear regression model. These assumptions ensure that the OLS estimators are unbiased, efficient, and have desirable statistical properties.</p>
<p>The Gauss-Markov assumptions are as follows:</p>
<ol type="1">
<li><p><strong>Linearity</strong>: The relationship between the dependent variable and the independent variables is linear in the population model. This means that the true relationship between the variables can be represented by a linear equation.</p></li>
<li><p><strong>Independence</strong>: The errors (residuals) in the regression model are independent of each other. This assumption ensures that the errors for one observation do not depend on or influence the errors for other observations.</p></li>
<li><p><strong>Strict exogeneity</strong>: The errors have a mean of zero conditional on all the independent variables. In other words, the expected value of the errors is not systematically related to any of the independent variables.</p></li>
<li><p><strong>No perfect multicollinearity</strong>: The independent variables are not perfectly correlated with each other. Perfect multicollinearity occurs when one independent variable is a perfect linear combination of other independent variables, leading to problems in estimating the regression coefficients.</p></li>
<li><p><strong>Homoscedasticity</strong>: The errors have constant variance (homoscedasticity) across all levels of the independent variables. This assumption implies that the spread or dispersion of the errors is the same for all values of the independent variables.</p></li>
<li><p><strong>No endogeneity</strong>: The errors are not correlated with any of the independent variables. Endogeneity occurs when there is a correlation between the errors and one or more of the independent variables, leading to biased and inefficient estimators.</p></li>
<li><p><strong>No autocorrelation</strong>: The errors are not correlated with each other, meaning that there is no systematic pattern or relationship between the errors for different observations.</p></li>
</ol>
<p>These assumptions collectively ensure that the OLS estimators are unbiased, efficient, and have minimum variance among all linear unbiased estimators. Violations of these assumptions can lead to biased and inefficient estimators, invalid hypothesis tests, and unreliable predictions. Therefore, it is important to check these assumptions when using the OLS method and consider alternative estimation techniques if the assumptions are violated.</p>
</section>
</section>
<section id="how-to-identify-statistically-significant-estimated-coefficients-in-a-regression-analysis" class="level2 page-columns page-full" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="how-to-identify-statistically-significant-estimated-coefficients-in-a-regression-analysis"><span class="header-section-number">5.3</span> How to identify statistically significant estimated coefficients in a regression analysis</h2>
<section id="p-values" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="p-values"><span class="header-section-number">5.3.1</span> P-values</h3>
<p>When you perform regression analysis, the results are often presented in a table that includes p-values. Understanding these p-values is essential to determine whether the relationships between your variables are statistically significant.</p>
<p>The p-value tells us the probability that the coefficient (effect) we observe is due to random chance rather than a real relationship. Thus, it ranges theoretically from 0 to 1.</p>
<ol type="1">
<li><strong>Threshold for Significance</strong><br>
Commonly used thresholds (also called significance levels) are:
<ul>
<li>0.05 (5% significance level)</li>
<li>0.01 (1% significance level)</li>
<li>0.001 (0.1% significance level)</li>
</ul></li>
<li><strong>Decision Rule for a 5% significance level:</strong>
<ul>
<li><strong>P-Value &lt; 0.05:</strong> The result is considered statistically significant. There is strong evidence that the coefficient (relationship) is not due to random chance.</li>
<li><strong>P-Value ≥ 0.05:</strong> The result is not considered statistically significant. There is not enough evidence to say that the coefficient is different from zero (no relationship).</li>
</ul></li>
</ol>
<p>Here is an example of a stylized regression table:</p>
<table class="table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Coefficient</th>
<th>P-Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>2.5</td>
<td>0.0001</td>
</tr>
<tr class="even">
<td>Study Hours</td>
<td>0.8</td>
<td>0.0005</td>
</tr>
<tr class="odd">
<td>Sleep Hours</td>
<td>0.1</td>
<td>0.0450</td>
</tr>
<tr class="even">
<td>TV Watching</td>
<td>-0.3</td>
<td>0.0600</td>
</tr>
</tbody>
</table>
<p>How can we interpret the p-values:</p>
<ul>
<li><p><strong>Intercept (P-Value: 0.0001):</strong> The p-value is much less than 0.05, indicating the intercept is statistically significant. This means the starting value (when all other variables are zero) is not due to chance.</p></li>
<li><p><strong>Study Hours (P-Value: 0.0005):</strong> The p-value is less than 0.05, so the coefficient for Study Hours is statistically significant. This means there is strong evidence that more study hours are associated with higher scores, and this relationship is unlikely to be due to chance.</p></li>
<li><p><strong>Sleep Hours (P-Value: 0.0450):</strong> The p-value is slightly less than 0.05, indicating that the coefficient for Sleep Hours is statistically significant. There is some evidence that more sleep hours are associated with higher scores.</p></li>
<li><p><strong>TV Watching (P-Value: 0.0600):</strong> The p-value is greater than 0.05, meaning the coefficient for TV Watching is not statistically significant. There isn’t strong enough evidence to conclude that TV Watching affects scores.</p></li>
</ul>
<p><strong>Summary:</strong></p>
<ul>
<li>P-values help you determine the significance of your results.</li>
<li>A p-value less than 0.05 typically indicates a significant result, meaning the variable likely has an effect.</li>
<li>A p-value greater than 0.05 suggests the variable’s effect is not statistically significant, and any observed relationship might be due to chance.</li>
</ul>
</section>
<section id="t-values" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="t-values"><span class="header-section-number">5.3.2</span> t-values</h3>
<p>Understanding t-values helps to determine whether the relationships between your variables are statistically significant.</p>
<p>The t-value measures how many standard deviations the estimated coefficient is away from zero. It helps us understand if the coefficient is significantly different from zero (no effect).</p>
<ol type="1">
<li><strong>Threshold for Significance:</strong>
<ul>
<li>The significance of a t-value depends on the chosen significance level (e.g., 0.05) and the degrees of freedom in the regression model.</li>
<li>In regression analysis, “degrees of freedom” refer to the number of independent values that can vary in the calculation of a statistic, typically calculated as the number of observations minus the number of estimated parameters (including the intercept). This concept helps adjust the precision of the estimates and the validity of the statistical tests used in the analysis.</li>
<li>A common rule of thumb is that a t-value greater than approximately 2 (or less than -2) indicates statistical significance at the 0.05 level.</li>
<li>A little bit more precise is the value 1.96. It is often called the “magic number” as it is crucial in statistics because it marks the cutoff for a 95% confidence interval in a standard normal distribution, meaning 95% of data lies within 1.96 standard deviations of the mean. This makes it a key threshold for determining statistical significance in hypothesis testing at the 5% significance level.</li>
</ul></li>
<li><strong>Decision Rule:</strong>
<ul>
<li><strong>|t-Value| &gt; 1.96:</strong> The result is considered statistically significant. There is strong evidence that the coefficient (relationship) is not zero.</li>
<li><strong>|t-Value| ≤ 1.96:</strong> The result is not considered statistically significant. There is not enough evidence to say that the coefficient is different from zero (no relationship).</li>
</ul></li>
</ol>
<p>Here is an example of a stylized regression table:</p>
<table class="table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Coefficient</th>
<th>T-Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>2.5</td>
<td>5.0</td>
</tr>
<tr class="even">
<td>Study Hours</td>
<td>0.8</td>
<td>4.0</td>
</tr>
<tr class="odd">
<td>Sleep Hours</td>
<td>0.1</td>
<td>1.89</td>
</tr>
<tr class="even">
<td>TV Watching</td>
<td>-0.3</td>
<td>-2.1</td>
</tr>
</tbody>
</table>
<p>How can we interpret the t-values:</p>
<ul>
<li><p><strong>Intercept (T-Value: 5.0):</strong> The t-value is much greater than 2, indicating the intercept is statistically significant. This means the starting value (when all other variables are zero) is not due to chance.</p></li>
<li><p><strong>Study Hours (T-Value: 4.0):</strong> The t-value is greater than 2, so the coefficient for Study Hours is statistically significant. This means there is strong evidence that more study hours are associated with higher scores, and this relationship is unlikely to be due to chance.</p></li>
<li><p><strong>Sleep Hours (T-Value: 1.89):</strong> The t-value is less than 2 in absolute values. This indicates that the coefficient for Sleep Hours may be statistically insignificant, suggesting no evidence that more sleep hours are associated with higher scores.</p></li>
<li><p><strong>TV Watching (T-Value: -2.1):</strong> The t-value is -2.1, which is more than 2 in absolute values. This suggests that there might be some evidence that more TV watching is associated with lower scores.</p></li>
</ul>
<p><strong>Summary:</strong></p>
<ul>
<li>T-values help you determine the significance of your estimated coefficients.</li>
<li>A t-value greater than 2 (or less than -2) typically indicates a significant result, meaning the variable likely has an effect.</li>
<li>A t-value between -2 and 2 suggests the variable’s effect is not statistically significant, and any observed relationship might be due to chance.</li>
</ul>
</section>
<section id="standard-error" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="standard-error"><span class="header-section-number">5.3.3</span> Standard Error</h3>
<p>Understanding the standard error also helps to assess regression estimates. It measures the average distance that the observed values fall from the regression line. It provides an estimate of the variability of the coefficient.</p>
<p>The standard error (SE) of a coefficient quantifies the precision of the coefficient estimate. Smaller standard errors indicate more precise estimates.</p>
<p><strong>Interpreting SE:</strong></p>
<ul>
<li><strong>Small SE:</strong> Indicates that the estimated coefficient is precise and likely to be close to the true population value.</li>
<li><strong>Large SE:</strong> Suggests more variability in the estimate, making it less reliable and potentially due to random chance.</li>
</ul>
<p>Here is an example of stylized regression table might look like, including standard errors:</p>
<table class="table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Coefficient</th>
<th>Standard error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>2.5</td>
<td>0.5</td>
</tr>
<tr class="even">
<td>Study Hours</td>
<td>0.8</td>
<td>0.2</td>
</tr>
<tr class="odd">
<td>Party Hours</td>
<td>-0.5</td>
<td>0.05</td>
</tr>
<tr class="even">
<td>TV Watching</td>
<td>-0.3</td>
<td>0.15</td>
</tr>
</tbody>
</table>
<p>Unfortunately, the standard error itself does not allow to judge on an estimate. However, knowing the estimate and the SE allows us to calculate the t-values as follows:</p>
<p>Let <span class="math inline">\(\hat{\alpha }\)</span> be an estimator of parameter <span class="math inline">\(\alpha\)</span> in some statistical model. Then a t-statistic for this parameter is any quantity of the form<br>
<span class="math display">\[
t_{\hat {\alpha }}={\frac {{\hat {\alpha }}-\alpha _{0}}{s.e. ({\hat{\alpha }})}}
\left(=\frac{\text{estimated value - hypothesized value}}{\text{standard error of the estimator}}\right)
\]</span></p>
<p><strong>Calculating t-values</strong></p>
<p>We can calculate the t-values for each coefficient using the formula:</p>
<p><span class="math display">\[
t_{\hat{\alpha}} = \frac{\hat{\alpha}}{s.e.(\hat{\alpha})}
\]</span></p>
<p>Given the regression table:</p>
<table class="table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Coefficient</th>
<th>Standard Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>2.5</td>
<td>0.5</td>
</tr>
<tr class="even">
<td>Study Hours</td>
<td>0.8</td>
<td>0.2</td>
</tr>
<tr class="odd">
<td>Party Hours</td>
<td>-0.5</td>
<td>0.05</td>
</tr>
<tr class="even">
<td>TV Watching</td>
<td>-0.3</td>
<td>0.15</td>
</tr>
</tbody>
</table>
<p>We calculate the t-values as follows:</p>
<ol type="1">
<li><p><strong>Intercept:</strong> <span class="math display">\[
t_{\text{Intercept}} = \frac{2.5}{0.5} = 5.0
\]</span></p></li>
<li><p><strong>Study Hours:</strong> <span class="math display">\[
t_{\text{Study Hours}} = \frac{0.8}{0.2} = 4.0
\]</span></p></li>
<li><p><strong>Party Hours:</strong> <span class="math display">\[
t_{\text{Party Hours}} = \frac{-0.5}{0.05} = -10.0
\]</span></p></li>
<li><p><strong>TV Watching:</strong> <span class="math display">\[
t_{\text{TV Watching}} = \frac{-0.3}{0.15} = -2.0
\]</span></p></li>
</ol>
<p>Here’s the updated table with the t-values:</p>
<table class="table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Coefficient</th>
<th>Standard Error</th>
<th>T-Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>2.5</td>
<td>0.5</td>
<td>5.0</td>
</tr>
<tr class="even">
<td>Study Hours</td>
<td>0.8</td>
<td>0.2</td>
<td>4.0</td>
</tr>
<tr class="odd">
<td>Party Hours</td>
<td>-0.5</td>
<td>0.05</td>
<td>-10.0</td>
</tr>
<tr class="even">
<td>TV Watching</td>
<td>-0.3</td>
<td>0.15</td>
<td>-2.0</td>
</tr>
</tbody>
</table>
<p><strong>Explanation of the T-Values:</strong></p>
<ul>
<li><strong>Intercept (t-value: 5.0):</strong> The t-value of 5.0 indicates that the intercept is highly significant.</li>
<li><strong>Study Hours (t-value: 4.0):</strong> The t-value of 4.0 suggests that the coefficient for Study Hours is statistically significant.</li>
<li><strong>Party Hours (t-value: -10.0):</strong> The t-value of -10.0 shows a highly significant negative effect of Party Hours on the dependent variable.</li>
<li><strong>TV Watching (t-value: -2.0):</strong> The t-value of -2.0 indicates that the coefficient for TV Watching is significant, but less so compared to the other variables.</li>
</ul>
<div id="tip-nicani" class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip&nbsp;5.1: Statistical control requires causal justification
</div>
</div>
<div class="callout-body-container callout-body">
<p>Read <a href="identification.html#sec-scrcj" class="quarto-xref"><span>Section 3.4</span></a> (again).</p>
</div>
</div>
<p>A confounding variable is a factor that was not accounted for or controlled in a study but has the potential to influence the results. In other words, the true effects of the treatment or intervention can be obscured or muddled by the presence of this variable.</p>
<p>For instance, let’s consider a scenario where two groups of individuals are observed: one group took vitamin C daily, while the other group did not. Over the course of a year, the number of colds experienced by each group is recorded. It might be observed that the group taking vitamin C had fewer colds compared to the group that did not. However, it would be incorrect to conclude that vitamin C directly reduces the occurrence of colds. Since this study is observational and not a true experiment, numerous confounding variables are at play. One potential confounding variable could be the individuals’ level of health consciousness. Those who take vitamins regularly might also engage in other health-conscious behaviors, such as frequent handwashing, which could independently contribute to a lower risk of catching colds.</p>
<p>To address confounding variables, researchers employ control measures. The idea is to create conditions where confounding variables are minimized or eliminated. In the aforementioned example, researchers could pair individuals who have similar levels of health consciousness and randomly assign one person from each pair to take vitamin C daily (while the other person receives a placebo). Any differences observed in the number of colds between the groups would be more likely attributable to the vitamin C, compared to the original observational study. Well-designed experiments are crucial as they actively control for potential confounding variables.</p>
<p>Consider another scenario where a researcher claims that eating seaweed prolongs life. However, upon reading interviews with the study subjects, it becomes apparent that they were all over 100 years old, followed a very healthy diet, slept an average of 8 hours per day, drank ample water, and engaged in regular exercise. In this case, it is not possible to determine whether longevity was specifically caused by seaweed consumption due to the presence of numerous confounding variables. The healthy diet, sufficient sleep, hydration, and exercise could all independently contribute to longer life. These variables act as confounding factors.</p>
<p>A common error in research studies is to fail to control for confounding variables, leaving the results open to scrutiny. The best way to head off confounding variables is to do a well-designed experiment in a controlled setting. Observational studies are great for surveys and polls, but not for showing cause-and-effect relationships, because they don’t control for confounding variables.</p>
<p><strong>Control variables</strong> are usually variables that you are not particularly interested in, but that are related to the dependent variable. You want to remove their effects from the equation. A control variable enters a regression in the same way as an independent variable – the method is the same.</p>
<div id="tip-nicani" class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip&nbsp;5.2
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nick Huntington-Klein offers <a href="https://www.nickchk.com/causalgraphs.html">Causal Inference Animated Plots</a> on his homepage. Read this page and consider the animated graphs.</p>
</div>
</div>
</section>
<section id="omitted-variable-bias-and-ceteris-paribus" class="level3 page-columns page-full" data-number="5.3.4">
<h3 data-number="5.3.4" class="anchored" data-anchor-id="omitted-variable-bias-and-ceteris-paribus"><span class="header-section-number">5.3.4</span> Omitted variable bias and ceteris paribus</h3>
<p>From the Gauss-Markov theorem we know that if the OLS assumptions are fulfilled, the OLS estimator is (in the sense of smallest variance) the best linear conditionally unbiased estimator (BLUE). However, OLS estimates can suffer from omitted variable bias when any regressor, X, is correlated with any omitted variable that matters for variable Y.</p>
<p>For omitted variable bias to occur, two conditions must be fulfilled:</p>
<ol type="1">
<li>X is correlated with the omitted variable.</li>
<li>The omitted variable is a determinant of the dependent variable Y.</li>
</ol>
<p>In regression analysis, “ceteris paribus” is a Latin phrase that translates to “all other things being equal” or “holding everything else constant.” It is a concept used to examine the relationship between two variables while assuming that all other factors or variables remain unchanged.</p>
<p>When we say <em>ceteris paribus</em> in the context of regression analysis, we are isolating the effect of a specific independent variable on the dependent variable while assuming that the values of the other independent variables remain constant. By holding other variables constant, we can focus on understanding the direct relationship between the variables of interest.</p>
<p>For example, consider a regression analysis that examines the relationship between income (dependent variable) and education level (independent variable) while controlling for age, gender, and work experience. By stating <em>ceteris paribus</em>, we are assuming that age, gender, and work experience remain constant, and we are solely interested in understanding the impact of education level on income.</p>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-lookatoutput" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.1</strong></span> Look at the Output</p>
<div id="fig-regstata2" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-regstata2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.5: Regression output
</figcaption>
<div aria-describedby="fig-regstata2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/reg_stata2.png" class="img-fluid figure-img" style="width:75.0%">
</div>
</figure>
</div>
<p>In <a href="#fig-regstata2" class="quarto-xref">Figure&nbsp;<span>5.5</span></a> you see an excerpt of a regression output taken from a statistical program named <em>Stata</em>. Some t-values and p-values are missing.</p>
<ol type="a">
<li>Calculate the t-value of the coefficient <code>mpg</code>. Is the coefficient at a level of <span class="math inline">\(\alpha=0.05\)</span> statistically significant?<br>
</li>
<li>Is the coefficient foreign at a level of <span class="math inline">\(\alpha=0.05\)</span> statistically significant?<br>
</li>
<li>Is the constant at a level of <span class="math inline">\(\alpha=0.05\)</span> statistically significant?</li>
</ol>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-exrstataoutput" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.2</strong></span> Look at Stata Output</p>
<p>In <a href="#fig-regstata3" class="quarto-xref">Figure&nbsp;<span>5.6</span></a> you find two regression outputs from Stata. Try to interpret the p-values and the confidence intervals. How are the t-values calculated. Can you use the <em>magic number</em> 1.96 to say if a corresponding estimated coefficient is statistically significant, or not? Which estimated model is <em>better</em>?</p>
<div id="fig-regstata3" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-regstata3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.6: Stata regression output
</figcaption>
<div aria-describedby="fig-regstata3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<figcaption>Output A</figcaption>
<p><img src="fig/reg_stata_class2.png" class="img-fluid figure-img" style="width:75.0%"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<figcaption>Output B</figcaption>
<p><img src="fig/reg_stata_class.png" class="img-fluid figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</figure>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-execal" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.3</strong></span> Explain the weight (<a href="https://raw.githubusercontent.com/hubchev/courses/main/scr/exe_calories.R">Solutions online</a>)</p>
<p>In the following exercise you need to use the programming language R.</p>
<ol type="a">
<li>Write down your name, your matriculation number, and the date.<br>
</li>
<li>Set your working directory.<br>
</li>
<li>Clear your global environment.<br>
</li>
<li>Load the following package: <code>tidyverse</code></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The following table stems from a survey carried out at the Campus of the German Sport University of Cologne at Opening Day (first day of the new semester) between 8:00am and 8:20am. The survey consists of 6 individuals with the following information:</p>
<div id="tbl-dtacol" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dtacol-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.1: Dataset collected in Cologne
</figcaption>
<div aria-describedby="tbl-dtacol-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th>id</th>
<th>sex</th>
<th>age</th>
<th>weight</th>
<th>calories</th>
<th>sport</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>f</td>
<td>21</td>
<td>48</td>
<td>1700</td>
<td>60</td>
</tr>
<tr class="even">
<td>2</td>
<td>f</td>
<td>19</td>
<td>55</td>
<td>1800</td>
<td>120</td>
</tr>
<tr class="odd">
<td>3</td>
<td>f</td>
<td>23</td>
<td>50</td>
<td>2300</td>
<td>180</td>
</tr>
<tr class="even">
<td>4</td>
<td>m</td>
<td>18</td>
<td>71</td>
<td>2000</td>
<td>60</td>
</tr>
<tr class="odd">
<td>5</td>
<td>m</td>
<td>20</td>
<td>77</td>
<td>2800</td>
<td>240</td>
</tr>
<tr class="even">
<td>6</td>
<td>m</td>
<td>61</td>
<td>85</td>
<td>2500</td>
<td>30</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Data Description:</p>
<ul>
<li><strong>id:</strong> Variable with an anonymized identifier for each participant.</li>
<li><strong>sex:</strong> Gender, i.e., the participants replied to be either male (m) or female (f).</li>
<li><strong>age:</strong> The age in years of the participants at the time of the survey.</li>
<li><strong>weight:</strong> Number of kg the participants pretended to weight.</li>
<li><strong>calories:</strong> Estimate of the participants on their average daily consumption of calories.</li>
<li><strong>sport:</strong> Estimate of the participants on their average daily time that they spend on doing sports (measured in minutes).</li>
</ul>
<p>Which type of data do we have here? (Panel data, repeated cross-sectional data, cross-sectional data, time Series data)</p>
<p>Store each of the five variables in a vector and put all five variables into a dataframe with the title <code>df</code>. If you fail here, read in the data using this line of code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/hubchev/courses/main/dta/df-calories.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="7" type="a">
<li><p>Show for all numerical variables the summary statistics including the mean, median, minimum, and the maximum.</p></li>
<li><p>Show for all numerical variables the summary statistics including the mean and the standard deviation, <strong>separated by male and female</strong>. Use therefore the pipe operator.</p></li>
<li><p>Suppose you want to analyze the general impact of average calories consumption per day on the weight. Discuss if the sample design is appropriate to draw conclusions on the population. What may cause some bias in the data? Discuss possibilities to improve the sampling and the survey, respectively.</p></li>
<li><p>The following plot visualizes the two variables weight and calories. Discuss what can be improved in the graphical visualization.</p></li>
</ol>
<div id="fig-sport-r" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-sport-r-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.7: Weight vs.&nbsp;Calories
</figcaption>
<div aria-describedby="fig-sport-r-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/sport-r.png" class="img-fluid figure-img" style="width:60.0%">
</div>
</figure>
</div>
<ol start="11" type="a">
<li><p>Create a scatterplot matrix to visualize relationships between all numerical variables in the dataset.</p></li>
<li><p>Calculate the Pearson Correlation Coefficient for the following pairs of variables:</p>
<ul>
<li><code>calories</code> and <code>sport</code></li>
<li><code>weight</code> and <code>calories</code></li>
</ul>
<p>This will help in understanding the strength and direction of the linear relationship between these variables.</p></li>
<li><p>Generate a scatterplot with <code>weight</code> on the y-axis and <code>calories</code> on the x-axis. Include a linear fit to the data and label the points with the <code>sex</code> variable. This visualization can provide insights into the relationship between calorie consumption and weight, differentiated by gender.</p></li>
<li><p>Estimate the following regression specification using the Ordinary Least Squares (OLS) method:</p></li>
</ol>
<p><span class="math display">\[
weight_i=\beta_0+\beta_1 calories_i+ \epsilon_i
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># OLS Regression</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>reg_base <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> calories, <span class="at">data =</span> df)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg_base)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="15" type="a">
<li><p>Interpret the results. In particular, interpret how many kg the estimated weight increases—on average and ceteris paribus—if calories increase by 100 calories. Additionally, discuss the statistical properties of the estimated coefficient <span class="math inline">\(\hat{\beta_1}\)</span> and the meaning of the <em>Adjusted R-squared</em>.</p></li>
<li><p>OLS estimates can suffer from omitted variable bias. State the two conditions that need to be fulfilled for omitted bias to occur.</p></li>
<li><p>Discuss potential confounding variables that may cause omitted variable bias. Given the dataset above how can some of the confounding variables be <em>controlled for</em>?</p></li>
</ol>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-causalgraphnhk" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.4</strong></span> Causal inference and animated plots</p>
<p>Nick <span class="citation" data-cites="Huntington-Klein2022Effect">Huntington-Klein (<a href="references.html#ref-Huntington-Klein2022Effect" role="doc-biblioref">2022</a>)</span> has created wonderful animated graphs that give great and quick insights into how causal inference works. Please read his online chapter on <a href="https://www.nickchk.com/causalgraphs.html"><em>Causal Inference Animated Plots</em></a> and discuss</p>
<ol type="a">
<li>what he means when he speaks of <em>closing the back-door path</em> and <em>controlling for</em>,</li>
<li>what methods exist to <em>close the back-door path</em>, and</li>
<li>why it is sometimes necessary to omit variables from an estimated regression model.</li>
</ol>
</div>
</div>
</div>
</div>
<div class="no-row-height column-margin column-container"><div id="ref-Huntington-Klein2022Effect" class="csl-entry" role="listitem">
Huntington-Klein, N. (2022). <em>The effect: An introduction to research design and causality</em>. Accessed January 30, 2023; CRC Press. <a href="https://theeffectbook.net">https://theeffectbook.net</a>
</div></div></section>
</section>
<section id="difference-in-difference" class="level2 page-columns page-full" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="difference-in-difference"><span class="header-section-number">5.4</span> Difference in difference</h2>
<div id="fig-dcard" class="quarto-figure quarto-figure-center quarto-float anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-dcard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.8: David Card (*1956)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>
</figcaption>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;Source: <a href="https://davidcard.berkeley.edu/">https://davidcard.berkeley.edu/</a>.</p></div></div><div aria-describedby="fig-dcard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/dcard1.jpg" class="img-fluid figure-img" style="width:25.0%">
</div>
</figure>
</div>
<p>David Card is one of the most influential labor economist of the 20th century and Nobel laureate of 2021. He is well-known for his research on the effects of the minimum wage on employment, which challenged the traditional view that increasing the minimum wage leads to a decrease in employment. In his article <em>Minimum Wages and Employment: A Case Study of the Fast-Food Industry in New Jersey and Pennsylvania</em> <span class="citation" data-cites="Card1994Minimum">(<a href="references.html#ref-Card1994Minimum" role="doc-biblioref">Card &amp; Krueger, 1994</a>)</span> he and Alan Krueger (1960-2019) used a <em>natural experiment</em> to examine the effect of an increase in the minimum wage on employment. In particular, they identified a treatment group (restaurants in New Jersey) and a control group (restaurants in eastern Pennsylvania) to measure the effect of increasing the minimum wage that was increased in New Jersey but not in Pennsylvania. This increase did not lead to a decrease in employment, which contradicted the widely held view that increasing the minimum wage would lead to job loss. The empirical method that they used is called <em>difference in difference</em> and we discuss it in the following section.</p>
<div class="no-row-height column-margin column-container"><div id="ref-Card1994Minimum" class="csl-entry" role="listitem">
Card, D., &amp; Krueger, A. B. (1994). Minimum wages and employment: A case study of the fast-food industry in new jersey and pennsylvania. <em>The American Economic Review</em>, <em>84</em>(4), 772–793.
</div></div><p>The difference in difference (DiD) method allows to estimate the causal effect of a treatment or intervention. In particular, it is popular to study the impact of policy changes and other interventions on a specific outcome of interest.</p>
<p>The basic idea behind the DiD method is to compare the change in an outcome variable between a treatment group and a control group over time. The treatment group is the group that is exposed to the intervention or treatment, while the control group is a group that is not exposed to the intervention. The difference in the change in the outcome variable between the two groups is then used to estimate the causal effect of the intervention.</p>
<p>To use the DiD method, researchers typically collect data on the outcome variable of interest for both the treatment and control groups before and after the intervention. This data is then used to calculate the difference in the change in the outcome variable between the two groups.</p>
<p>For example, if a study aims to examine the effect of a new policy on the employment rate, it should collect data on the employment rate for a group of individuals living in a region where the policy was implemented, and for a group living in a similar region where the policy was not implemented. The study can then compare the change in the employment rate for the two groups, before and after the implementation of the policy. The difference in the change in the employment rate between the two groups can be used to estimate of the causal effect of the policy on employment.</p>
<p>It is important to note that DiD assumes that there are no other factors that could be affecting the outcome variable of interest and that the treatment and control groups are similar in all ways except for the intervention. To control for these assumptions researchers can use statistical techniques such as matching to ensure that treatment and control groups are similar before the intervention.</p>
<p>DiD is useful when we only have observational data and in situations where it is not possible or ethical to randomly assign individuals to a treatment or control group, for example, in the case of policy changes.</p>
<div id="tip-neal9" class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip&nbsp;5.3
</div>
</div>
<div class="callout-body-container callout-body">
<p>Differences-in-Differences and Rubin causal model</p>
<div id="fig-neal9" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-neal9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.9: Differences-in-Differences
</figcaption>
<div aria-describedby="fig-neal9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/neal9.png" class="img-fluid figure-img" style="width:90.0%">
</div>
</figure>
</div>
<div id="fig-neal9b" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-neal9b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.10: Tolerate time-invariant unobserved confounding
</figcaption>
<div aria-describedby="fig-neal9b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/neal9b.png" class="img-fluid figure-img" style="width:90.0%">
</div>
</figure>
</div>
<p>Figures <a href="#fig-neal9" class="quarto-xref"><span>5.9</span></a> and <a href="#fig-neal9b" class="quarto-xref"><span>5.10</span></a> stem from a video of Brady Neal’s lecture on <a href="https://youtu.be/2nDgrNP7XSE"><em>Difference-in-Differences</em></a>. Please watch this video.</p>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-DiD" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.5</strong></span> Mastering DiD with Joshua Angrist</p>
<div id="fig-angristdid" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-angristdid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.11: Josh Angrist (*1960): Nobel Prize winner of economics in 2021
</figcaption>
<div aria-describedby="fig-angristdid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/angrist-did.png" class="img-fluid figure-img" style="width:50.0%">
</div>
</figure>
</div>
<p>Watch the video <a href="https://youtu.be/eiffOVbYvNc"><em>Introduction to Differences-in-Differences</em></a> and answer the following questions. The video is part of a course called <em>Mastering Econometrics with Joshua Angrist (MIT)</em> produced by Marginal Revolution University. In it, Josh Angrist introduces differences within differences using one of the worst economic events in history: the Great Depression.</p>
<ol type="1">
<li>In the video, the treatment being examined is:
<ol type="a">
<li>Bank failure.</li>
<li>“Easy” money.</li>
<li>“Tight” money.</li>
<li>Differences-in-Differences.</li>
<li>None of the above.</li>
</ol></li>
<li>If the treatment were effective, which outcome would we expect to observe?
<ol type="a">
<li>Fewer bank failures.</li>
<li>Increased bank failures.</li>
<li>Continued parallel trends.</li>
<li>No differences in any variables unrelated to bank failure.</li>
<li>None of the above.</li>
</ol></li>
<li>Practically, how is DD (Differences-in-Differences) typically implemented?
<ol type="a">
<li>Non-parametric statistical techniques.</li>
<li>Randomized trials.</li>
<li>Regression analysis.</li>
<li>Instrumental variables.</li>
<li>None of the above.</li>
</ol></li>
</ol>
<p>See <a href="#sol-DiD" class="quarto-xref">Solution&nbsp;<span>5.1</span></a></p>
</div>
</div>
</div>
</div>
</section>
<section id="solutions-to-the-exercises" class="level2 unlisted unnumbered">
<h2 class="unlisted unnumbered anchored" data-anchor-id="solutions-to-the-exercises">Solutions to the exercises</h2>
<div class="callout callout-style-simple callout-tip no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="sol-DiD" class="proof solution">
<p><span class="proof-title"><em>Solution 5.1</em>. </span>Solution to exercise <a href="#exr-DiD" class="quarto-xref">Exercise&nbsp;<span>5.5</span></a></p>
<p>Answers: 1. b), 2. a), 3. c)</p>
</div>
</div>
</div>
</div>



</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./statistics.html" class="pagination-link" aria-label="Statistics">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Statistics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./experiments.html" class="pagination-link" aria-label="Experiments">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Experiments</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>