---
title: "How to Use R for Data Science"
subtitle: "Lecture Notes"
author: "© Prof. Dr. Stephan Huber (Stephan.Huber@hs-fresenius.de)"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
link-citations: true
header-includes:
   - \usepackage{tikz}
documentclass: book
output:
  bookdown::pdf_book:
    highlight: default
    toc: yes
    toc_depth: 3
  bookdown::gitbook:
    split_bib: no
site: bookdown::bookdown_site
classoption: oneside
citation_package: natbib
biblio-style: apacite
fontsize: 12pt
bibliography: book.bib
urlcolor: blue
linkcolor: red
number_sections: yes
---



# Preface  {.unnumbered}

## About the notes {.unlisted .unnumbered}

- This script aims to support my lecture at the HS Fresenius. It is incomplete and no substitute for taking actively part in class. 
- The old version of the notes can be found here <a href="https://github.com/hubchev/hubchev.github.io/raw/main/various/rcourse_book.pdf" target="_blank">PDF.</a> 
- I appreciate you reading it, and I appreciate any comments. 
- This is work in progress so please check for updates regularly. 
- The lecture notes are available online or you can download it as a [pdf file here](https://raw.githubusercontent.com/hubchev/hubchev.github.io/main/ds/_main.pdf)
- These notes are published under a Creative Commons BY-SA license (CC BY-SA) version 4.0. This means it can be reused, remixed, retained, revised and redistributed as long as appropriate credit is given to the authors. If you remix, or modify the original version of this open textbook, you must redistribute all versions of this open textbook under the same license---CC BY-SA. This script is build on the work of @Navarro2020Learning, @Muschelli2022Introduction, @Thulin2021Modern, and @Ismay2022Statistical  which is also published under CC BY-SA.


## About the author  {.unlisted .unnumbered}

![(\#fig:itsme) Prof. Dr. Stephan Huber^[Picture is taken from https://sites.google.com/view/stephanhuber]](fig/huber2.jpeg){ width=25% }
   
Prof. Dr. Stephan Huber is Professor of International Economics and Data Science at *HS Fresenius* and holds a Diploma in Economics from the *University of Regensburg* and a Doctoral Degree (summa cum laude) from the University of Trier. He completed postgraduate studies at the *Interdisciplinary Graduate Center of Excellence at the Institute for Labor Law and Industrial Relations in the European Union (IAAEU)* in Trier. He was a research assistant to Prof. Dr. Dr. h.c. Joachim Möller at the *University of Regensburg*, post-doc at the *Leibniz Institute for East and Southeast European Studies (IOS)* in Regensburg and freelancer at *Charles University* in Prague.
   
He has worked as a lecturer at various institutions including the _TU Munich_, the *University of Regensburg*, *Saarland University*, and the *Universities of Applied Sciences in Frankfurt and Augsburg*. He has also taught abroad for the *University of Cordoba* in Spain and the *University of Perugia*. Professor Huber has published his work in  international journals such as the *Canadian Journal of Economics* and the *Stata Journal*. More on his work can be found on his private homepage [www.t1p.de/stephanhuber](https://www.t1p.de/stephanhuber).
   
**Contact**
     
```
   Hochschule Fresenius für Wirtschaft & Medien GmbH
   Im MediaPark 4c
   50670 Cologne
   
   Office: 4b OG-1 Bü01 (Office hour: Thursday 1-2 p.m.)
   Telefon: +49 221 973199-523
   Mail: stephan.huber@hs-fresenius.de
   Private homepage: www.t1p.de/stephanhuber
   Github: https://github.com/hubchev

```
   



