<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Monetary international economics – Economics (INCOMPLETE)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./trade.html" rel="next">
<link href="./gdp.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b53751a350365c71b6c909e95f209ed1.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-790c112f69e88879aaf3be921f200e21.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-54bf09cdc62f08ecb5bf749e3c6659fd.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./monetary.html">International Economics</a></li><li class="breadcrumb-item"><a href="./monetary.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Monetary international economics</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Economics (INCOMPLETE)</a> 
        <div class="sidebar-tools-main">
    <a href="./Economics--INCOMPLETE-.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Introduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./scope.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Scope</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./free.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Perfect markets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Methods</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Core</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gdp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Measuring welfare</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">International Economics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./monetary.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Monetary international economics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./trade.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">International trade</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./policy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Trade policy</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">tba</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anecdote.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">From anecdote to insight</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./micro_prelim.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Microeconomic preliminaries</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./math_prelim.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Mathematical preliminaries</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exams.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Past exams</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#currencies" id="toc-currencies" class="nav-link active" data-scroll-target="#currencies"><span class="header-section-number">5.1</span> Currencies</a>
  <ul class="collapse">
  <li><a href="#exchange-rates" id="toc-exchange-rates" class="nav-link" data-scroll-target="#exchange-rates"><span class="header-section-number">5.1.1</span> Exchange rates</a></li>
  <li><a href="#relative-prices-and-exchange-rates" id="toc-relative-prices-and-exchange-rates" class="nav-link" data-scroll-target="#relative-prices-and-exchange-rates"><span class="header-section-number">5.1.2</span> Relative prices and exchange rates</a></li>
  <li><a href="#sec-exraimportant" id="toc-sec-exraimportant" class="nav-link" data-scroll-target="#sec-exraimportant"><span class="header-section-number">5.1.3</span> The importance of exchange rates</a></li>
  <li><a href="#trump-relative-prices-and-trade-policy" id="toc-trump-relative-prices-and-trade-policy" class="nav-link" data-scroll-target="#trump-relative-prices-and-trade-policy"><span class="header-section-number">5.1.4</span> Trump, relative prices, and trade policy</a></li>
  <li><a href="#sec-FOREX" id="toc-sec-FOREX" class="nav-link" data-scroll-target="#sec-FOREX"><span class="header-section-number">5.1.5</span> The FOREX</a></li>
  <li><a href="#sec-pppa" id="toc-sec-pppa" class="nav-link" data-scroll-target="#sec-pppa"><span class="header-section-number">5.1.6</span> Purchasing power parity assumption</a></li>
  </ul></li>
  <li><a href="#sec-International-investments" id="toc-sec-International-investments" class="nav-link" data-scroll-target="#sec-International-investments"><span class="header-section-number">5.2</span> International investments</a>
  <ul class="collapse">
  <li><a href="#foreign-exchange-reserves" id="toc-foreign-exchange-reserves" class="nav-link" data-scroll-target="#foreign-exchange-reserves"><span class="header-section-number">5.2.1</span> Foreign exchange reserves</a></li>
  <li><a href="#three-components-of-the-rate-of-return" id="toc-three-components-of-the-rate-of-return" class="nav-link" data-scroll-target="#three-components-of-the-rate-of-return"><span class="header-section-number">5.2.2</span> Three components of the rate of return</a></li>
  <li><a href="#rate-of-return-of-an-investment-abroad" id="toc-rate-of-return-of-an-investment-abroad" class="nav-link" data-scroll-target="#rate-of-return-of-an-investment-abroad"><span class="header-section-number">5.2.3</span> Rate of return of an investment abroad</a></li>
  <li><a href="#sec-inparcon" id="toc-sec-inparcon" class="nav-link" data-scroll-target="#sec-inparcon"><span class="header-section-number">5.2.4</span> The interest parity condition</a></li>
  <li><a href="#the-theory-in-real-markets-unpegging-the-swiss-franc" id="toc-the-theory-in-real-markets-unpegging-the-swiss-franc" class="nav-link" data-scroll-target="#the-theory-in-real-markets-unpegging-the-swiss-franc"><span class="header-section-number">5.2.5</span> The theory in real markets: Unpegging the Swiss Franc</a></li>
  <li><a href="#the-fisher-effect" id="toc-the-fisher-effect" class="nav-link" data-scroll-target="#the-fisher-effect"><span class="header-section-number">5.2.6</span> The Fisher Effect</a></li>
  </ul></li>
  <li><a href="#sec-bofpayments" id="toc-sec-bofpayments" class="nav-link" data-scroll-target="#sec-bofpayments"><span class="header-section-number">5.3</span> Balance of payments</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">5.3.1</span> Introduction</a></li>
  <li><a href="#the-payments-must-be-balanced" id="toc-the-payments-must-be-balanced" class="nav-link" data-scroll-target="#the-payments-must-be-balanced"><span class="header-section-number">5.3.2</span> The payments must be balanced!</a></li>
  <li><a href="#a-normative-discussion-of-imbalances-in-the-capital-and-current-account" id="toc-a-normative-discussion-of-imbalances-in-the-capital-and-current-account" class="nav-link" data-scroll-target="#a-normative-discussion-of-imbalances-in-the-capital-and-current-account"><span class="header-section-number">5.3.3</span> A normative discussion of imbalances in the capital and current account</a></li>
  <li><a href="#a-formal-representation" id="toc-a-formal-representation" class="nav-link" data-scroll-target="#a-formal-representation"><span class="header-section-number">5.3.4</span> A formal representation</a></li>
  <li><a href="#case-study-u.s.-trade-deficit" id="toc-case-study-u.s.-trade-deficit" class="nav-link" data-scroll-target="#case-study-u.s.-trade-deficit"><span class="header-section-number">5.3.5</span> Case study: U.S. trade deficit</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./monetary.html">International Economics</a></li><li class="breadcrumb-item"><a href="./monetary.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Monetary international economics</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-monetary" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Monetary international economics</span></span></h1>
</div>



<div class="quarto-title-meta column-body">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note no-icon callout-titled" title="Students learn to...">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Students learn to…
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>…interpret exchange rates and relate their changes to the relative prices of countries’ goods.</li>
<li>…predict the impact of exchange rate changes on business decisions and national economies.</li>
<li>…understand the linkage between interest rates and inflation in open economies.</li>
<li>…explain the interest rate parity condition and the purchasing power parity assumption.</li>
<li>…interpret and evaluate the balances of trade and</li>
</ul>
</div>
</div>
<section id="currencies" class="level2 page-columns page-full" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="currencies"><span class="header-section-number">5.1</span> Currencies</h2>
<p>An exchange rate indicates the value of one currency in relation to another. Exchange rate fluctuations have a significant impact on the revenues, costs, and profits of businesses; they affect how much you can afford to spend and can even influence job security.</p>
<p>Please work on the questions posed in <a href="#exr-intromonetary" class="quarto-xref">Exercise&nbsp;<span>5.1</span></a> and <a href="#exr-trumplira" class="quarto-xref">Exercise&nbsp;<span>5.2</span></a>. They are designed to motivate an introduction the topic.</p>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-intromonetary" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.1</strong></span> Exchange rates over time</p>
<div id="fig-fredgraph" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-fredgraph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Canadian Dollars to U.S. Dollar Exchange Rate
</figcaption>
<div aria-describedby="fig-fredgraph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="fig/fredgraph.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;5.1: Canadian Dollars to U.S. Dollar Exchange Rate"><img src="fig/fredgraph.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
</figure>
</div>
<ol type="a">
<li>As can be seen in <a href="#fig-fredgraph" class="quarto-xref">Figure&nbsp;<span>5.1</span></a>, 1 United States Dollar (USD) equals about 1.38 Canadian Dollar (CAD) today. Since January 2002, has the USD depreciated (lost value) or appreciated (gained value) against the CAD? Explain your decision.</li>
</ol>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>To determine whether the USD has depreciated or appreciated against the CAD since January 2002, we need to compare the current exchange rate to the rate from January 2002. The exchange rate in January 2002 was about <span class="math display">\[ 1 \text{USD} = 1.6 \text{CAD}.\]</span> The exchange rate in January 2024 is about <span class="math display">\[1 \text{USD} = 1.38 \text{CAD}.\]</span></p>
<p>That means, if you convert 1 USD in 2024, you get less CAD as compared to converting 1 USD in January 2002. In other words, it takes less CAD in 2024 to get 1 USD compared to the year 2002. Thus, the USD has <em>depreciated</em> against the CAD. In turn, the CAD has <em>appreciated</em>.</p></li>
</ol>
</div>
</div>
</div>
<ol start="2" type="a">
<li>Assume that in January 2002, you exchanged a total of 2000 USD to Canadian Dollars (CAD) at a rate of 1.6 CAD per USD. Calculate how much that amount is worth today in USD.</li>
</ol>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol start="2" type="a">
<li><p>Having exchanged 2000 CAD into USD in 2002 at an exchange rate of $ 1 = 1.6 $ leaves you with <span class="math display">\[2000 \ \text{USD} \cdot 1.6 \frac{\text{CAD}}{\text{USD}} = 3200 \, \text{CAD}.\]</span> If you convert these 3200 CAD to USD in 2024 at an exchange rate of <span class="math inline">\(\text{USD} = 1.38 \text{CAD}\)</span> you end up with <span class="math display">\[
3200 \text{CAD} \cdot  \frac{1}{1.38}  \frac{\text{USD}}{\text{CAD}} \approx 2318.84\ \text{USD}.
\]</span></p>
<p>This means that you end up with USD 318.84 more, which corresponds to an increase of around 15.9%. The reason for this gain is that you have invested in a currency that has appreciated. Therefore, holding a currency can be considered a form of investment.</p></li>
</ol>
</div>
</div>
</div>
<ol start="3" type="a">
<li><p>Suppose you have 1000 USD today, that is January 2024, and you plan to invest it in a Canadian fund that assures you a 2% annual interest rate.</p>
<ol type="i">
<li>Calculate how much USD you’ll have after one year if the exchange rate remains on its current level of 1.38 CAD per USD.</li>
<li>Calculate how much USD you’ll have after one year if the exchange rate slightly chances to 1.42 CAD per USD.</li>
</ol></li>
</ol>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol start="3" type="a">
<li><p>First, you convert your USD to CAD in January 2024: <span class="math display">\[1000 \ \text{USD} \cdot 1.38 \frac{\text{CAD}}{\text{USD}} = 1380 \, \text{CAD}.\]</span> Then, you invest the CAD receiving 2% of interest after 1 year: <span class="math display">\[1380 \text{CAD} \cdot 1.02 = 1407.6\ \text{CAD}.\]</span> Finally, you convert the CAD back to USD</p>
<ol type="i">
<li>at the rate 1.38 CAD per USD: <span class="math display">\[
1407.6\ \text{CAD} \cdot  \frac{1}{1.38}  \frac{\text{USD}}{\text{CAD}} = 1020\ \text{USD}.
\]</span></li>
<li>at the rate 1.42 CAD per USD: <span class="math display">\[
1407.6\ \text{CAD} \cdot  \frac{1}{1.42}  \frac{\text{USD}}{\text{CAD}} \approx 991.27\ \text{USD}.
\]</span></li>
</ol></li>
</ol>
<p>This means that if you expect the exchange rate to remain unchanged, the Canadian fund could be a reasonable investment, offering a 2% return. However, if you anticipate that the CAD will depreciate by more than 2%, it would not be a profitable investment.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-trumplira" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.2</strong></span> Our relations are not good</p>
<div id="fig-trumplira" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-trumplira-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: Trump doubles metal tariffs on Turkey by 20%
</figcaption>
<div aria-describedby="fig-trumplira-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="fig/trump_lira_pdf.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;5.2: Trump doubles metal tariffs on Turkey by 20%"><img src="fig/trump_lira_pdf.png" class="img-fluid figure-img" style="width:70.0%"></a></p>
<p><em>Source: Twitter</em></p>
</div>
</figure>
</div>
<p>Why is Trump implicitly expressing concerns about the weak Lira and the strong Dollar? Would he prefer a “strong” Turkish Lira and a “weak” Dollar? What factors actually contribute to his satisfaction? Can you understand the logic behind President Trump’s decision to double metal tariffs in response to the decline of the Turkish Lira (see <a href="#fig-trumplira" class="quarto-xref">Figure&nbsp;<span>5.2</span></a>)? Discuss.</p>
</div>
</div>
</div>
</div>
<section id="exchange-rates" class="level3 page-columns page-full" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="exchange-rates"><span class="header-section-number">5.1.1</span> Exchange rates</h3>
<p>The most important economic indicators frequently discussed in the media and politics are Gross Domestic Product (GDP)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, the policy rate<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, and the inflation rate<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. These measures are designed to explain the functioning of economic markets and guide policymakers. However, the exchange rate is used less frequently in political and public debates, which I believe is a significant oversight for several reasons.</p>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;The total value added of a country in a given period</p></div><div id="fn2"><p><sup>2</sup>&nbsp;The interest rate set by a central bank that influences the lending and borrowing rates of commercial banks to control inflation, manage employment levels, and stabilize the currency</p></div><div id="fn3"><p><sup>3</sup>&nbsp;The percentage increase in the general price level of goods and services in an economy over a given period</p></div></div><p>Firstly, similar to the aforementioned measures, exchange rate movements have a substantial impact on both markets and individuals. Moreover, the exchange rate serves as an accurate measure that reflects real market movements more quickly than most other indicators. Overall, a solid understanding of exchange rates is crucial for making informed decisions, managing financial risks, optimizing operations, and strategically positioning companies in the global marketplace.</p>
<p>Before I explain this in greater detail, let me share my explanations for why the exchange rate is relatively unnoticed in public debates:</p>
<ul>
<li><strong>Complexity of interpretation:</strong> It is comparatively difficult to interpret. GDP should be rising, while the inflation and policy rates should ideally be low. In contrast, the exchange rate is not so straightforward because there isn’t a universally optimal exchange rate that everyone hopes for. The ideal rate depends on many factors, such as whether you want to buy goods from abroad or sell them to the rest of the world. Different stakeholders and investors will have varying preferences about the exchange rate. Many people, especially politicians, avoid the complexities of “it depends” arguments because it is challenging to make convincing cases based on intricate relationships.</li>
<li><strong>Volatility:</strong> The exchange rate is comparatively volatile, and its changes are difficult to predict.</li>
<li><strong>Multiple exchange rates:</strong> There isn’t just one exchange rate; there are many, as any currency can be exchanged for any other currency. This means that a country’s exchange rate may rise against currency A but fall against currency B.</li>
<li><strong>Limited political influence:</strong> The power of politics to directly and measurably influence a country’s exchange rate is limited.</li>
<li><strong>Understanding requirements:</strong> The impact of exchange rate movements on our lives requires a solid understanding of economic markets, which many people lack.</li>
</ul>
<p>While I cannot change the factors that contribute to the limited discussion of exchange rates, I can work to help you make sense of this topic. Before discussing the importance of the exchange rate in <a href="#sec-exraimportant" class="quarto-xref"><span>Section 5.1.3</span></a>, let’s first define the rate:</p>
<div class="callout callout-style-default callout-note callout-titled" title="Exchange Rate">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exchange Rate
</div>
</div>
<div class="callout-body-container callout-body">
<p>The price of one currency in terms of another is called an exchange rate. Exchange rates allow us to compare the prices of goods and services across countries, determining a country’s relative prices for exports and imports.</p>
</div>
</div>
<p>To define the rate more formally, suppose the Euro (€) is the home currency and Turkish Lira (₺) the foreign currency, then the exchange rate in direct quotation (Preisnotierung) is <span class="math display">\[E^{\frac{\text{€}}{\text{₺}}}=\frac{X \text{€}}{Y \text{₺}}\]</span> and the exchange rate in indirect quotation (Mengennotierung) is <span class="math display">\[E^{\frac{\text{₺}}{\text{€}}}=\frac{Y \text{₺}}{X \text{€}}.\]</span></p>
<p>Both rates contain the same information, but have different interpretations:</p>
<ul>
<li><span class="math inline">\(E^{\frac{\text{€}}{\text{₺}}}\)</span> tells that we have to give X to receive Y , whereas</li>
<li><span class="math inline">\(E^{\frac{\text{₺}}{\text{€}}}\)</span> tells that we have to give Y to receive X .</li>
</ul>
<p>Alternative interpretations:</p>
<ul>
<li><span class="math inline">\(E^{\frac{\text{€}}{\text{₺}}}\)</span> tells that we have to give <span class="math inline">\(\frac{X}{Y} \text{€}\)</span> to receive 1 , whereas</li>
<li><span class="math inline">\(E^{\frac{\text{₺}}{\text{€}}}\)</span> tells that we have to give <span class="math inline">\(\frac{Y}{X} \text{₺}\)</span> to receive 1 .</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="Appreciation / Depreciation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Appreciation / Depreciation
</div>
</div>
<div class="callout-body-container callout-body">
<p>A currency can appreciate or depreciate relative to other currencies.</p>
<ul>
<li>If the appreciates, <span class="math inline">\(E^{\frac{\text{€}}{\text{₺}}}\)</span> decreases and <span class="math inline">\(E^{\frac{\text{₺}}{\text{€}}}\)</span> increases.</li>
<li>If the depreciates, <span class="math inline">\(E^{\frac{\text{€}}{\text{₺}}}\)</span> increases and <span class="math inline">\(E^{\frac{\text{₺}}{\text{€}}}\)</span> decreases.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Conventions to talk about exchange rates:">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Conventions to talk about exchange rates:
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><em>Euro to Dollar</em> means <span class="math inline">\(\frac{\text{€}}{\$}\)</span> (This is especially confusing and it can also be understood the other way round but the first currency mentioned is <em>usually</em> interpreted as the numerator)</li>
<li><em>Euro per Dollar</em> means <span class="math inline">\(\frac{\text{€}}{\$}\)</span></li>
<li><em>Euro in Dollar</em> means <span class="math inline">\(\frac{\$}{\text{€}}\)</span></li>
<li><em>1 Euro costs X Dollars</em> means X <span class="math inline">\(\frac{\$}{\text{€}}\)</span></li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-eurotodollar" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.3</strong></span> Interpret the exchange rate representations shown in <a href="#fig-eurotodollar" class="quarto-xref">Figure&nbsp;<span>5.3</span></a>. Consider the Euro as the home currency and write the most recent currency rates of the four figures in direct quotation.</p>
<div id="fig-eurotodollar" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-eurotodollar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.3: Euro to Dollar
</figcaption>
<div aria-describedby="fig-eurotodollar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-eurotodollar" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-eurotodollar1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-fig" id="fig-eurotodollar1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a)
</figcaption>
<div aria-describedby="fig-eurotodollar1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="fig/eurotodollar1.jpeg" class="lightbox" data-gallery="fig-eurotodollar" title="Figure&nbsp;5.3&nbsp;(a): "><img src="fig/eurotodollar1.jpeg" id="fig-eurotodollar1" class="img-fluid figure-img" data-ref-parent="fig-eurotodollar"></a>
</div>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-eurotodollar" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-eurotodollar2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-fig" id="fig-eurotodollar2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b)
</figcaption>
<div aria-describedby="fig-eurotodollar2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="fig/eurotodollar2.jpeg" class="lightbox" data-gallery="fig-eurotodollar" title="Figure&nbsp;5.3&nbsp;(b): "><img src="fig/eurotodollar2.jpeg" id="fig-eurotodollar2" class="img-fluid figure-img" data-ref-parent="fig-eurotodollar"></a>
</div>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-eurotodollar" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-eurotodollar3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-fig" id="fig-eurotodollar3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c)
</figcaption>
<div aria-describedby="fig-eurotodollar3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="fig/eurotodollar3.png" class="lightbox" data-gallery="fig-eurotodollar" title="Figure&nbsp;5.3&nbsp;(c): "><img src="fig/eurotodollar3.png" id="fig-eurotodollar3" class="img-fluid figure-img" data-ref-parent="fig-eurotodollar"></a>
</div>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-eurotodollar" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-eurotodollar4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-fig" id="fig-eurotodollar4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d)
</figcaption>
<div aria-describedby="fig-eurotodollar4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="fig/eurotodollar4.png" class="lightbox" data-gallery="fig-eurotodollar" title="Figure&nbsp;5.3&nbsp;(d): "><img src="fig/eurotodollar4.png" id="fig-eurotodollar4" class="img-fluid figure-img" data-ref-parent="fig-eurotodollar"></a>
</div>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<p><em>Source: Subfigures (c) and (d) are taken from Google.</em></p>
</div>
</div>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The exchange rate in direct quotation is:</p>
<ol type="a">
<li><p><span class="math display">\[E^{\frac{\text{€}}{\text{\$}}}=\frac{X \text{€}}{Y \text{\$}} = \frac{1 \text{€}}{1,0212 \text{\$}}=0.97924011 \frac{\text{€}}{\text{\$}} \]</span> <a href="#fig-eurotodollar1" class="quarto-xref">Figure&nbsp;<span>5.3 (a)</span></a> is denoted in indirect quotation. From April 2014 to July 2022 the Euro depreciated as one Euro was equivalent to 1.3823 Dollar in April 2014 and only 1.0212 Dollar in July 2022.<br>
</p></li>
<li><p><span class="math display">\[E^{\frac{\text{€}}{\text{\$}}}=\frac{X \text{€}}{Y \text{\$}} = 1 \]</span> <a href="#fig-eurotodollar2" class="quarto-xref">Figure&nbsp;<span>5.3 (b)</span></a> is denoted in direct quotation. From early 2018 to mid 2022 the Euro depreciated as one Dollar was equivalent to 0.80 Euro in early 2018 and 1.00 Euro in mid 2022.</p></li>
<li><p><span class="math display">\[E^{\frac{\text{€}}{\text{\$}}}=\frac{X \text{€}}{Y \text{\$}} = \frac{1 \text{€}}{1,1050 \text{\$}}=0.904977376 \frac{\text{€}}{\text{\$}} \]</span> <a href="#fig-eurotodollar3" class="quarto-xref">Figure&nbsp;<span>5.3 (c)</span></a> is denoted in indirect quotation. From the beginning of the graph somewhen 2019 till 9th of September 2024 the Euro depreciated as one Euro was equivalent to 1.1680 Dollar in 2019 and is now worth 1.1050 Dollar in July 2022.<br>
</p></li>
<li><p><span class="math display">\[E^{\frac{\text{€}}{\text{\$}}}=\frac{X \text{€}}{Y \text{\$}} = \frac{1 \text{€}}{1,0212 \text{\$}}= 0.904731747\frac{\text{€}}{\text{\$}} \]</span> <a href="#fig-eurotodollar4" class="quarto-xref">Figure&nbsp;<span>5.3 (d)</span></a> is denoted in indirect quotation. For example, from the 2nd of January 2021 to the 9th of September 2024 the Euro depreciated as one Euro was equivalent to 1.2011 Dollar in January 2021 and 1.1053 Dollar in July 2022.</p></li>
</ol>
<p>Please note that Googles “EUR / USD” notation is misleading as it does not mean that the exchange rate is denoted in direct quotation, that is, <span class="math inline">\(\frac{X \text{€}}{Y \text{\$}}\)</span>.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-tradecurrencies" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.4</strong></span> Exchange currencies</p>
<p>Suppose 1 US Dollar (USD) is equivalent to 1.20 Euros (EUR).</p>
<ol type="a">
<li>Calculate the equivalent amount in Euros if a person exchanges 500 US Dollars.</li>
<li>If the exchange rate changes to <span class="math inline">\(1.15 \frac{USD}{EUR}\)</span>, recalculate the equivalent amount in Euros for the same 500 US Dollars.</li>
<li>If the exchange rate changes to <span class="math inline">\(1.15 \frac{USD}{EUR}\)</span>, has the Euro appreciated or depreciated?</li>
<li>A European tourist plans to spend 1,000 Euros during a trip to the United States. Calculate the equivalent amount in US Dollars at the exchange rate of <span class="math inline">\(1.15 \frac{EUR}{USD}\)</span>.</li>
</ol>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>The equivalent amount in Euros for exchanging 500 US Dollars at the initial exchange rate of (1.20 , ) is given by: <span class="math display">\[
\text{Equivalent Euros} = \frac{500 \, \text{USD}}{1.20 \, \text{USD/EUR}}
\]</span></p></li>
<li><p>If the exchange rate changes to (1.15 , ), the new equivalent amount in Euros is: <span class="math display">\[
\text{New Equivalent Euros} = \frac{500 \, \text{USD}}{1.15 \, \text{USD/EUR}}
\]</span></p></li>
<li><p>The equivalent amount in US Dollars for spending 1,000 Euros at the initial exchange rate is: <span class="math display">\[
\text{Equivalent USD} = 1,000 \, \text{EUR} \times 1.20 \, \text{USD/EUR}
\]</span></p></li>
<li><p>If the European tourist exchanges their money at the changed rate of (1.15 , ), the new equivalent amount in US Dollars is:</p></li>
</ol>
<p><span class="math display">\[
\text{New Equivalent USD} = 1,000 \, \text{EUR} \times 1.15 \, \text{USD/EUR}
\]</span></p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="relative-prices-and-exchange-rates" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="relative-prices-and-exchange-rates"><span class="header-section-number">5.1.2</span> Relative prices and exchange rates</h3>
<p>After understanding the concept of exchange rates, let us consider how trade in goods between two countries operates when each country uses a different currency as its legal tender.</p>
<p>Let us consider a stylized example: Assume the home country produces beer and the foreign country produces wine. If you want to exchange a beer for wine, the relative price indicates the amount of beer you need to provide in order to receive a unit of wine (in direct quotation) or the quantity of wine you will receive for a unit of beer (in indirect quotation).</p>
<p>For example, a relative price of 1 means you can exchange 1 liter of beer for 1 liter of wine. However, if we assume that beer is measured in 500 ml cans and wine in 1-liter bottles, the relative price denoted with <span class="math inline">\(P^{\frac{beer}{wine}}\)</span> would be represented as:</p>
<p><span class="math display">\[P^{\frac{beer}{wine}}= \frac{2 \text{ cans of beer}}{1 \text{ bottle of wine}}.\]</span></p>
<p>This means you can exchange 2 cans of beer for one bottle of wine.</p>
<p>If the relative price increases, you will need to provide more beer to receive a bottle of wine. Conversely, if the relative price decreases, you will need to provide less beer to obtain a bottle of wine.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Relative prices">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Relative prices
</div>
</div>
<div class="callout-body-container callout-body">
<p>Relative prices determine the relative price of commodities across countries. For example, an increase in the price of foreign commodities makes imported commodities relatively more expensive and home commodities relatively cheaper for buyers at home.</p>
</div>
</div>
<p>Relative prices are (directly) determined by exchange rates. To logically prove this statement, let us assume for simplicity an exchange rate of 1, <span class="math display">\[E^{\frac{\text{₺}}{\text{€}}}=E^{\frac{\text{€}}{\text{₺}}}=1\]</span> and that a liter of beer costs 1 € at home and a wine costs 1 ₺ abroad. Thus, we can buy both a wine or a beer for 1 €. Due to the fact that we must pay the wine producer with ₺, we must convert the € beforehand. The process goes like visualized in <a href="#fig-curex1" class="quarto-xref">Figure&nbsp;<span>5.4</span></a>:</p>
<div id="fig-curex1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-curex1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.4: One wine per Euro
</figcaption>
<div aria-describedby="fig-curex1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="fig/curex1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;5.4: One wine per Euro"><img src="fig/curex1.png" class="img-fluid figure-img"></a>
</div>
</figure>
</div>
<p>Now, assume that the € appreciates and the exchange rate becomes <span class="math inline">\(E^{\frac{\text{€}}{\text{₺}}}=0.5\)</span> and <span class="math inline">\(E^{\frac{\text{₺}}{\text{€}}}=2\)</span>, respectively. Then, you receive more than one wine if we assume that the price of wine in ₺ remains unchanged. The process is visualized in <a href="#fig-curex2" class="quarto-xref">Figure&nbsp;<span>5.5</span></a>:</p>
<div id="fig-curex2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-curex2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.5: Two wine per Euro
</figcaption>
<div aria-describedby="fig-curex2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="fig/curex2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure&nbsp;5.5: Two wine per Euro"><img src="fig/curex2.png" class="img-fluid figure-img"></a>
</div>
</figure>
</div>
<p>That means, exchange rates determine the relative prices. If the home currency appreciates (depreciates), buying goods and services abroad becomes relative cheaper (more expensive).</p>
<p>Of course, if many people now buy wine and aim to convert € &nbsp;to ₺, this may impact the exchange rate and the price of wine. We come back to that later.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Exchange rates and relative prices">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exchange rates and relative prices
</div>
</div>
<div class="callout-body-container callout-body">
<p>The exchange rate determines the relative price of commodities across countries. For example, an appreciation of a currency makes commodities more expensive for foreign buyers and in turn makes foreign commodities cheaper for buyers at home.</p>
</div>
</div>
</section>
<section id="sec-exraimportant" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="sec-exraimportant"><span class="header-section-number">5.1.3</span> The importance of exchange rates</h3>
<p>Here is an incomplete list of arguments to emphasize the importance of exchange rates for economies, businesses, and individuals:</p>
<ul>
<li><strong>Import/export costs</strong>: Exchange rate fluctuations determine the relative prices and hence affect the cost of importing goods and materials and the global demand for domestic products. An appreciation of the home currency makes imports relatively cheaper but exports more expensive for the rest of the world, while depreciation has the opposite effect.</li>
<li><strong>Revenue conversion</strong>: Multinational companies earn revenues in multiple currencies. Exchange rate changes can significantly impact the value of these revenues when converted back to the home currency, affecting overall profitability.</li>
<li><strong>Foreign investments</strong>: Companies investing in foreign assets or operations need to understand exchange rates to forecast returns accurately and manage exchange rate risk.</li>
<li><strong>Risk management</strong>: Knowledge of exchange rates enables businesses to hedge against currency risk using financial instruments like forwards, futures, options, and swaps. This is crucial for stabilizing cash flows and protecting profit margins.</li>
<li><strong>Market competitiveness</strong>: Exchange rates affect the relative cost competitiveness of goods and services in international markets. Companies need to understand these implications to price their products competitively and make strategic decisions about entering or exiting markets.</li>
<li><strong>Macroeconomic insights</strong>: Exchange rates are influenced by and also affect economic indicators such as inflation, interest rates, and economic growth. Understanding these relationships helps in making informed predictions about market conditions.</li>
<li><strong>Contractual agreements</strong>: Businesses engaged in international trade must understand exchange rates to negotiate and structure contracts effectively, determining terms such as the currency of payment and exchange rate clauses.</li>
<li><strong>Government and Policy Understanding</strong>: Exchange rates are often influenced by governmental and central bank policies. Understanding the dynamics between exchange rates and policy decisions is vital for anticipating regulatory changes and their potential impact on business operations.</li>
</ul>
</section>
<section id="trump-relative-prices-and-trade-policy" class="level3 page-columns page-full" data-number="5.1.4">
<h3 data-number="5.1.4" class="anchored" data-anchor-id="trump-relative-prices-and-trade-policy"><span class="header-section-number">5.1.4</span> Trump, relative prices, and trade policy</h3>
<p>Let’s return to Trump’s Twitter message . Steel producers in the U.S. (and Donald Trump himself) are unhappy about a strong dollar (and a weak Turkish Lira) because it makes their products relatively expensive for Turkish buyers while making Turkish steel relatively cheap for U.S. consumers.</p>
<p>Trump had two options to address this issue: altering the exchange rates or adjusting the relative prices of goods between countries. Changing the exchange rate directly is a challenging task. Although buying or selling currencies on the foreign exchange market can influence exchange rates, the market is so large that the actions Trump could take as President would have minimal impact (see <a href="#sec-FOREX" class="quarto-xref"><span>Section 5.1.5</span></a>). Adjusting policy rates could influence exchange rates more effectively, as we will discuss in <a href="#sec-International-investments" class="quarto-xref"><span>Section 5.2</span></a>. However, the Federal Reserve, which sets policy rates and thus has an impact on interest rates, operates independently from political orders. Consequently, Trump’s influence over their decisions is limited.</p>
<p>As a result, Trump chose to increase the price of foreign steel in the U.S. by introducing or raising tariffs. The approach works, American steel producing companies get protected from foreign competition and might sell more domestically. However, there many negative consequences that detoriate the overall welfare. Foremost, everybody in the U.S. must pay more for steel (and for products made with steel and aluminum). David Boaz, Executive Vice President of the Cato Institute, a libertarian think tank, highlights this issue in his response on Twitter (see <a href="#fig-trump_reply" class="quarto-xref">Figure&nbsp;<span>5.6</span></a>).</p>
<div id="fig-trump_reply" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-trump_reply-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.6: <em>Who wins in the end?</em>
</figcaption>
<div aria-describedby="fig-trump_reply-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="fig/trump_reply_pdf.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Figure&nbsp;5.6: Who wins in the end?"><img src="fig/trump_reply_pdf.png" class="img-fluid figure-img" style="width:70.0%"></a></p>
<p><em>Source: Twitter</em></p>
</div>
</figure>
</div>
<p>To quantify the costs of Mr.&nbsp;Trumps’s tariffs, let me quote the well-written article by <span class="citation" data-cites="Amiti2019impact">Amiti et al. (<a href="references.html#ref-Amiti2019impact" role="doc-biblioref">2019</a>)</span> (p.&nbsp;188-189):</p>
<div class="no-row-height column-margin column-container"><div id="ref-Amiti2019impact" class="csl-entry" role="listitem">
Amiti, M., Redding, S. J., &amp; Weinstein, D. E. (2019). The impact of the 2018 tariffs on prices and welfare. <em>Journal of Economic Perspectives</em>, <em>33</em>(4), 187–210.
</div></div><div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>“<em>We find that by December 2018, import tariffs were costing US consumers and the firms that import foreign goods an additional $3.2 billion per month in added tax costs and another $1.4 billion per month in deadweight welfare (efficiency) losses. Tariffs have also changed the pricing behavior of US producers by protecting them from foreign competition and enabling them to raise prices and markups, and we estimate that the combined effects of input and output tariffs have raised the average price of US manufacturing by 1 percentage point, which compares with an annual average rate of producer price inflation from 1990 to 2018 of just over 2 percentage points. US tariffs and the foreign retaliatory tariffs also affect international supply chains, and we estimate that if the tariffs that were in place by the end of 2018 were to continue, approximately $165 billion of trade per year will continue to be redirected in order to avoid the tariffs. We also show that the rise in tariffs has reduced the variety of products available to consumers.</em>”</p>
</div>
</div>
</div>
<p>In addition, it can be argued that increased tariffs might actually make the dollar stronger. If buyers stop purchasing steel from Turkey due to higher tariffs, they will need fewer Turkish lira and therefore will exchange fewer U.S. dollars for Turkish lira. This reduced demand for Turkish lira could lead to a stronger dollar.</p>
<p>While raising tariffs and initiating trade disputes could be a strategy to gain political support and possibly get re-elected, there is a general consensus among economists that raising tariffs usually leads to economic losses and detrimental outcomes for all countries involved.</p>
</section>
<section id="sec-FOREX" class="level3" data-number="5.1.5">
<h3 data-number="5.1.5" class="anchored" data-anchor-id="sec-FOREX"><span class="header-section-number">5.1.5</span> The FOREX</h3>
<section id="the-market" class="level4" data-number="5.1.5.1">
<h4 data-number="5.1.5.1" class="anchored" data-anchor-id="the-market"><span class="header-section-number">5.1.5.1</span> The market</h4>
<p>In a market, individuals exchange goods and services, offering something to receive something else in return. In the FOREX (foreign exchange market), participants exchange currencies. Like all markets, the price here is influenced by the supply and demand dynamics of currencies.</p>
<div id="fig-forexmarket" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-forexmarket-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.7: Example of a foreign exchange market
</figcaption>
<div aria-describedby="fig-forexmarket-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="fig/forexmarket.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Figure&nbsp;5.7: Example of a foreign exchange market"><img src="fig/forexmarket.png" class="img-fluid figure-img" style="width:70.0%"></a>
</div>
</figure>
</div>
<ul>
<li><strong>When the Euro (€) is considered strong, the exchange rate</strong> <span class="math inline">\(E^{\frac{\text{€}}{\text{₺}}}\)</span> is low:
<ul>
<li>At this lower exchange rate, there’s a high demand for Turkish Lira (₺) (point C), but the supply of ₺ is scarce (point E).</li>
<li>Consequently, the Euro faces depreciation pressure, leading to an increase in the exchange rate <span class="math inline">\(E^{\frac{\text{€}}{\text{₺}}} \uparrow\)</span>.</li>
</ul></li>
<li><strong>Conversely, when the Euro (€) is weak, the exchange rate</strong> <span class="math inline">\(E^{\frac{\text{€}}{\text{₺}}}\)</span> is high:
<ul>
<li>With the exchange rate high, the demand for ₺ drops (point A), while its supply burgeons (point F).</li>
<li>As a result, the Euro is under appreciation pressure, causing the exchange rate to decrease <span class="math inline">\(E^{\frac{\text{€}}{\text{₺}}} \downarrow\)</span>.</li>
</ul></li>
<li><strong>Point B represents the equilibrium exchange rate</strong>, where the demand for ₺ meets its supply. At this juncture, holders of ₺ are unwilling to part with more, and similarly, Euro holders are not inclined to exchange more.</li>
</ul>
<p>In 2022, the daily (!) traded volume of currencies averaged approximately $ 7,506 billion, as highlighted in <a href="#tbl-forexdaily" class="quarto-xref">Table&nbsp;<span>5.1</span></a>.</p>
<div class="{tbl-forexdaily}">
<div id="tbl-forexdaily" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-forexdaily-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.1: Daily turnover of global foreign exchange market from 2001 to 2022 (in billion U.S. dollars)
</figcaption>
<div aria-describedby="tbl-forexdaily-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>name</th>
<th style="text-align: right;">2001</th>
<th style="text-align: right;">2004</th>
<th style="text-align: right;">2007</th>
<th style="text-align: right;">2010</th>
<th style="text-align: right;">2013</th>
<th style="text-align: right;">2016</th>
<th style="text-align: right;">2019</th>
<th style="text-align: right;">2022</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">1.239</td>
<td style="text-align: right;">1.934</td>
<td style="text-align: right;">3.324</td>
<td style="text-align: right;">3.973</td>
<td style="text-align: right;">5.357</td>
<td style="text-align: right;">5.066</td>
<td style="text-align: right;">6.581</td>
<td style="text-align: right;">7.506</td>
</tr>
<tr class="even">
<td>USD</td>
<td style="text-align: right;">1.114</td>
<td style="text-align: right;">1.702</td>
<td style="text-align: right;">2.845</td>
<td style="text-align: right;">3.371</td>
<td style="text-align: right;">4.662</td>
<td style="text-align: right;">4.437</td>
<td style="text-align: right;">5.811</td>
<td style="text-align: right;">6.639</td>
</tr>
<tr class="odd">
<td>EUR</td>
<td style="text-align: right;">470</td>
<td style="text-align: right;">724</td>
<td style="text-align: right;">1.231</td>
<td style="text-align: right;">1.551</td>
<td style="text-align: right;">1.790</td>
<td style="text-align: right;">1.590</td>
<td style="text-align: right;">2.126</td>
<td style="text-align: right;">2.292</td>
</tr>
<tr class="even">
<td>JPY</td>
<td style="text-align: right;">292</td>
<td style="text-align: right;">403</td>
<td style="text-align: right;">573</td>
<td style="text-align: right;">754</td>
<td style="text-align: right;">1.235</td>
<td style="text-align: right;">1.096</td>
<td style="text-align: right;">1.108</td>
<td style="text-align: right;">1.253</td>
</tr>
<tr class="odd">
<td>GBP</td>
<td style="text-align: right;">162</td>
<td style="text-align: right;">319</td>
<td style="text-align: right;">494</td>
<td style="text-align: right;">512</td>
<td style="text-align: right;">633</td>
<td style="text-align: right;">649</td>
<td style="text-align: right;">843</td>
<td style="text-align: right;">968</td>
</tr>
<tr class="even">
<td>CNY</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">202</td>
<td style="text-align: right;">285</td>
<td style="text-align: right;">526</td>
</tr>
<tr class="odd">
<td>AUD</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">116</td>
<td style="text-align: right;">220</td>
<td style="text-align: right;">301</td>
<td style="text-align: right;">463</td>
<td style="text-align: right;">349</td>
<td style="text-align: right;">446</td>
<td style="text-align: right;">479</td>
</tr>
<tr class="even">
<td>CAD</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">143</td>
<td style="text-align: right;">210</td>
<td style="text-align: right;">244</td>
<td style="text-align: right;">260</td>
<td style="text-align: right;">332</td>
<td style="text-align: right;">466</td>
</tr>
<tr class="odd">
<td>CHF</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">117</td>
<td style="text-align: right;">227</td>
<td style="text-align: right;">250</td>
<td style="text-align: right;">276</td>
<td style="text-align: right;">243</td>
<td style="text-align: right;">326</td>
<td style="text-align: right;">390</td>
</tr>
<tr class="even">
<td>All others combined</td>
<td style="text-align: right;">170</td>
<td style="text-align: right;">251</td>
<td style="text-align: right;">568</td>
<td style="text-align: right;">786</td>
<td style="text-align: right;">1124</td>
<td style="text-align: right;">1223</td>
<td style="text-align: right;">1921</td>
<td style="text-align: right;">2093</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><em>Note: All others combined are: HKD, SGD, SEK, KRW, NOK, NZD, INR, MXN, TWD, ZAR, BRL, DKK, PLN, THB, ILS, IDR, CZK, AED, TRY, HUF, CLP, SAR, PHP, MYR.<br>
Source: https://github.com/TheEconomist/big-mac-data (July 18, 2018).</em></p>
</div>
</section>
<section id="actors-on-the-forex" class="level4" data-number="5.1.5.2">
<h4 data-number="5.1.5.2" class="anchored" data-anchor-id="actors-on-the-forex"><span class="header-section-number">5.1.5.2</span> Actors on the FOREX</h4>
<p>As indicated in <a href="#fig-forexplayer" class="quarto-xref">Figure&nbsp;<span>5.8</span></a>, there are several major players involved in trading on the foreign exchange market. In particular, commercial banks, multinational corporations and non-bank financial institutions, such as investment funds, play an important role in trading and speculation. Central banks also play a crucial role as they intervene to stabilize their national currency and thus influence the direction of the market.</p>
<div id="fig-forexplayer" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-forexplayer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.8: Players on the foreign exchange market
</figcaption>
<div aria-describedby="fig-forexplayer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><a href="fig/player_over.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Figure&nbsp;5.8: Players on the foreign exchange market"><img src="fig/player_over.jpg" class="img-fluid figure-img"></a></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><a href="fig/player_open.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Figure&nbsp;5.8: Players on the foreign exchange market"><img src="fig/player_open.jpg" class="img-fluid figure-img"></a></p>
</div>
</div>
</div>
</figure>
</div>
</section>
<section id="the-vehicle-currency" class="level4" data-number="5.1.5.3">
<h4 data-number="5.1.5.3" class="anchored" data-anchor-id="the-vehicle-currency"><span class="header-section-number">5.1.5.3</span> The vehicle currency</h4>
<p>Instead of converting directly between two less common currencies, it’s more efficient to use a broadly accepted and stable currency as a vehicle. That means, if you want to exchange currency A to B. You do not exchange currency A directly to B but you convert currency A first to the vehicle currency C and then from C to B.</p>
<p>As depicted in <a href="#fig-forex-ms" class="quarto-xref">Figure&nbsp;<span>5.9</span></a>, around 32% of all currency transactions included the Euro while a notable 88% involved the U.S. Dollar which makes the Dollar the standard vehicle currency. The Dollar acts as a medium in transactions between currencies that do not directly trade with high volume. This can reduce transaction costs and streamline the process.</p>
<div id="fig-forex-ms" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-forex-ms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.9: Market share of leading foreign exchange currencies in 2019
</figcaption>
<div aria-describedby="fig-forex-ms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="fig/forex-ms.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="Figure&nbsp;5.9: Market share of leading foreign exchange currencies in 2019"><img src="fig/forex-ms.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
</figure>
</div>
</section>
</section>
<section id="sec-pppa" class="level3" data-number="5.1.6">
<h3 data-number="5.1.6" class="anchored" data-anchor-id="sec-pppa"><span class="header-section-number">5.1.6</span> Purchasing power parity assumption</h3>
<p>The <strong>P</strong>urchasing <strong>P</strong>ower <strong>P</strong>arity (PPP) assumption is also know as the <strong>law of one price</strong>. It says that in competitive markets with zero transportation costs and no trade barriers, identical goods have the same price all over the world when expressed in terms of the same currency. The idea behind this is that if differences in prices exist, profits can be made through <strong>international arbitrage</strong>, that is, the process of buying a good cheap in one country and selling the good with a profit in another country. This process can quickly equalize real price differences across countries.</p>
<p>However, in the real world, prices differ substantially across countries (see the Big Mac Index in <a href="#tbl-bigmac" class="quarto-xref">Table&nbsp;<span>5.2</span></a> and <a href="#exr-bigmac" class="quarto-xref">Exercise&nbsp;<span>5.5</span></a>). The assumptions of the PPP do mostly not hold perfectly in reality: some goods and services are not trade-able, firms might have different degrees of market power across countries, and the transaction costs are not zero. Here are more reasons, why the PPP does not always apply, especially in the short run:</p>
<ul>
<li>Transportation costs are not zero. Shipping goods can be time consuming and expensive.</li>
<li>Many goods and services, such as real estate or personal services, cannot be traded.</li>
<li>International markets may be segmented due to regulatory barriers, tariffs and other trade restrictions.</li>
<li>Countries have different consumption preferences. That means, the same basket of goods is not necessarily equally demanded. The willingness to pay for goods vary across countries often significantly.</li>
<li>Countries impose different taxes and provide different subsidies on goods and services, which affects their prices and leads to deviations from PPPs.</li>
<li>Short-term fluctuations in exchange rates may deviate from the values predicted by PPPs due to speculation, interest rate differentials and other factors.</li>
<li>Differences in inflation rates between countries may lead to deviations from PPP, especially in the short run.</li>
<li>The same product may be perceived differently in different countries due to brand names, quality differences or local customization, resulting in different prices.</li>
<li>Regulations like warranty and product classifications are different and have an impact on the product and the willingness to pay for it.</li>
<li>Political instability, war or economic sanctions can affect currency values and prices and lead to deviations from PPP.</li>
<li>Prices of goods and services do not always adjust immediately to changes in the exchange rate, leading to short-term deviations from PPP.</li>
</ul>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-bigmac" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.5</strong></span> Big Mac Index</p>
<p>The differences of prices across countries can be illustrated with the Economist’s <em>Big Mac Index</em>. It indicates the price of a Big Mac in different countries in terms of the US Dollar. <a href="#tbl-bigmac" class="quarto-xref">Table&nbsp;<span>5.2</span></a> shows some countries with on average expensive and cheap Big Macs.</p>
<div id="tbl-bigmac" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-bigmac-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.2: The price of a Big Mac across countries
</figcaption>
<div aria-describedby="tbl-bigmac-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Country</th>
<th>Price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Switzerland</td>
<td>$6.57 (6.50 CHF)</td>
</tr>
<tr class="even">
<td>Sweden</td>
<td>$5.83 (51.00 SEK)</td>
</tr>
<tr class="odd">
<td>United States</td>
<td>$5.51 (5.51 USD)</td>
</tr>
<tr class="even">
<td>Norway</td>
<td>$5.22 (42 NOK)</td>
</tr>
<tr class="odd">
<td>Canada</td>
<td>$5.08 (6.65 CAD)</td>
</tr>
<tr class="even">
<td>Euro area</td>
<td>$4.75 (4.56 EUR)</td>
</tr>
<tr class="odd">
<td>…</td>
<td>…</td>
</tr>
<tr class="even">
<td>Egypt</td>
<td>$1.75 (31.37 EGP)</td>
</tr>
<tr class="odd">
<td>Ukraine</td>
<td>$1.91 (50 UAH)</td>
</tr>
<tr class="even">
<td>Russia</td>
<td>$2.09 (130 RUB)</td>
</tr>
<tr class="odd">
<td>Malaysia</td>
<td>$2.10 (8.45 MYR)</td>
</tr>
<tr class="even">
<td>Indonesia</td>
<td>$2.19 (31,500 IDR)</td>
</tr>
<tr class="odd">
<td>Taiwan</td>
<td>$2.27 (69 TWD)</td>
</tr>
</tbody>
</table>
<p><em>Source: https://github.com/TheEconomist/big-mac-data (July 18, 2018).</em></p>
</div>
</figure>
</div>
<ol type="a">
<li>Read <a href="https://en.wikipedia.org/wiki/Big_Mac_Index">Wikipedia’s page on the Big Mac Index</a> and discuss the <em>Big-Mac-Index</em> critically. Is it really a reasonable real-world measurement of purchasing power parity?</li>
<li>Compare the <em>Big-Mac-Index</em> to the <em>Mac-Index</em> (see: <a href="https://themacindex.com/">themacindex.com</a>) looking for price differences of the <em>Mac mini M1 256GB</em>. Why are the price differences for Apple products so much smaller compared to McDonald’s <em>Big Mac</em>? <em>In case the website offline, <a href="https://web.archive.org/web/20240831031732/https://themacindex.com/">here</a> is a snapshot of it.)</em></li>
<li>Using the data of <a href="#tbl-bigmac" class="quarto-xref">Table&nbsp;<span>5.2</span></a>, calculate the exchange rate of Euros (EUR) to Swiss Francs (CHF) in both the direct and the indirect quotation. Interpret your result.</li>
<li>Calculate how many Dollars you can buy with 100€. Then, use that dollars to buy Swiss Francs. How many Swiss Francs do you get?</li>
<li><em>Multiple choice:</em> Which of the following statements is true?
<ol type="i">
<li>The table indicates that the <em>Purchasing Power Parity Assumption</em> is fulfilled.</li>
<li>The exchange rate of US Dollar to Swiss Franc (CHF) is close to one.</li>
<li>The exchange rate of US Dollar to the Russian Ruble (RUB) is about <span class="math inline">\(62.2 \frac{\$}{RUB}\)</span>.</li>
<li>The exchange rate of Canadian Dollar (CAD) to the Euro (EUR) is about <span class="math inline">\(0.73\)</span>.</li>
<li>With one Canadian Dollar (CAD) you can buy <span class="math inline">\(0.73\)</span> US Dollars.</li>
</ol></li>
</ol>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution: Big Mac Index">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution: Big Mac Index
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>Please take part in the discussion in class.</p></li>
<li><p>Please take part in the discussion in class.</p></li>
<li><p>The exchange rate of Euros to Swiss Francs in direct quotation is: <span class="math display">\[E^{\frac{\text{ EUR}}{\text{ CHF}}}=\frac{4.56 \text{ EUR}}{4.75 \text{ USD}} \cdot \frac{6.57 \text{ USD}}{6.50 \text{ CHF}} = \frac{29.9592 \text{ EUR}}{30.875 \text{ CHF}} \approx 0.9703 \frac{\text{ EUR}}{\text{ CHF}}\]</span> and in indirect quotation: <span class="math display">\[E^{\frac{\text{ CHF}}{\text{ EUR}}} \approx 1.0305 \frac{\text{ CHF}}{\text{ EUR}}.\]</span> That means, we have to pay about 0.97 Euro for one Swiss Franc or one Euro costs about 1.03 Swiss Franc.</p></li>
<li><p>For 100 Euro we get <span class="math display">\[100 \text{ EUR} \cdot \frac{4.75 \text{ USD}}{4.56\text{ EUR}} \approx 104.16 \text{ USD}\]</span> and these can be converted to <span class="math display">\[104.16 \text{ USD} \cdot  \frac{6.50 \text{ CHF}}{6.57\text{ USD}} \approx 103.05 \text{ CHF}\]</span></p></li>
<li><p>Here are the answers:</p>
<ol type="i">
<li>is false: The price of a Big Mac in $&nbsp;is different across countries.</li>
<li>is correct.<br>
</li>
<li>is false: 1 Ruble costs 0.0160 Dollar: <span class="math display">\[ \frac{2.09\text{ USD}}{130 \text{ RUB}} = 0.016\frac{\text{ USD}}{\text{RUB}}.\]</span></li>
<li>is incorrect: <span class="math display">\[
\underbrace{\frac{6.65 \text{ CAD}}{5.08 \text{ USD}}}_{\approx 1.309}\cdot \underbrace{\frac{4.75 \text{ USD}}{4.56 \text{ EUR}}}_{\approx 1.0416} \approx 1.36\frac{\text{ CAD}}{\text{EUR}}.
\]</span></li>
<li>is incorrect: <span class="math display">\[
\frac{6.05 \text{ CAD}}{5.08 \text{ USD}} \approx 0.76 \frac{\text{ CAD}}{\text{ USD}}.
\]</span> Thus, with one Canadian Dollar you can buy 0.76 U.S. Dollar.</li>
</ol></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-arbitrage" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.6</strong></span> International arbitrage</p>
<div id="tbl-difprice" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-difprice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.3: Table of price variations across countries
</figcaption>
<div aria-describedby="tbl-difprice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Country</th>
<th>Price of Good <em>08/15</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Germany</td>
<td>$2</td>
</tr>
<tr class="even">
<td>Switzerland</td>
<td>$6</td>
</tr>
<tr class="odd">
<td>United States of America</td>
<td>$6</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<ol type="a">
<li><p>Consider a scenario where the good <em>08/15</em> is freely tradeable across countries without any cost (akin to digital software). You have $100, and upon examining the prices of <em>08/15</em> in three different countries, you notice discrepancies as depicted in <a href="#tbl-difprice" class="quarto-xref">Table&nbsp;<span>5.3</span></a>. Discuss how you could profit from <em>international arbitrage</em>, the practice of exploiting price differences of a good across countries. Describe the potential impact on the prices of the good once arbitrage begins.</p></li>
<li><p>Assuming <em>08/15</em> can be traded freely across borders like software, imagine your arbitrage efforts have harmonized the prices of the good worldwide, as illustrated in the <a href="#tbl-difcur" class="quarto-xref">Table&nbsp;<span>5.4</span></a>:</p></li>
</ol>
<div id="tbl-difcur" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-difcur-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.4: Table of prices and currencies across countries post-arbitrage
</figcaption>
<div aria-describedby="tbl-difcur-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Country</th>
<th>Price in USD</th>
<th>Price in Local Currency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Germany</td>
<td>$4</td>
<td>EUR 2</td>
</tr>
<tr class="even">
<td>Switzerland</td>
<td>$4</td>
<td>CHF 6</td>
</tr>
<tr class="odd">
<td>United States of America</td>
<td>$4</td>
<td>-</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Now, calculate and elucidate the following exchange rates:</p>
<ul>
<li><span class="math inline">\(\frac{\text{USD}}{\text{EUR}}\)</span></li>
<li><span class="math inline">\(\frac{\text{EUR}}{\text{USD}}\)</span></li>
<li><span class="math inline">\(\frac{\text{USD}}{\text{CHF}}\)</span></li>
<li><span class="math inline">\(\frac{\text{CHF}}{\text{USD}}\)</span></li>
<li><span class="math inline">\(\frac{\text{CHF}}{\text{EUR}}\)</span></li>
<li><span class="math inline">\(\frac{\text{EUR}}{\text{CHF}}\)</span></li>
</ul>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>International arbitrage strategy</p>
<ul>
<li><strong>Strategy</strong>: Buy 50 units of good <em>08/15</em> in Germany for $2 each with your $100. Then, sell these units in Switzerland or the USA for $6 each, making a total of $300. This is a classic arbitrage strategy.</li>
<li><strong>Impact on Prices</strong>: Consider that you repeat that winning strategy to buy in Germany and sell in some other country, prices will change: The increased demand in Germany will cause the price there to rise, while the increased supply in Switzerland and the USA will cause the price to drop. Eventually, the price differences will equalize, eliminating the arbitrage opportunity.</li>
</ul></li>
<li><p>Calculating exchange rates</p></li>
</ol>
<ul>
<li><p><strong>USD to EUR</strong>: <span class="math inline">\(\frac{4 USD}{2 EUR} = 2\frac{USD}{EUR}\)</span></p></li>
<li><p><strong>EUR to USD</strong>: <span class="math inline">\(0.5 \frac{EUR}{USD}\)</span></p></li>
<li><p><strong>USD to CHF</strong>: <span class="math inline">\(\frac{2}{3} \frac{USD}{CHF}\)</span></p></li>
<li><p><strong>CHF to USD</strong>: <span class="math inline">\(1.5 \frac{CHF}{USD}\)</span></p></li>
<li><p><strong>CHF to EUR</strong>: <span class="math inline">\(\frac{3}{1} \frac{CHF}{USD}\)</span></p></li>
<li><p><strong>EUR to CHF</strong>: <span class="math inline">\(\frac{1}{3} \frac{EUR}{CHF}\)</span></p></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-brexit" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.7</strong></span> Brexit and the exchange rate</p>
<p>Examine <a href="#fig-sinkflug" class="quarto-xref">Figure&nbsp;<span>5.10</span></a> and discuss the reasons behind the depreciation of the British pound since June 2016.</p>
<div id="fig-sinkflug" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-sinkflug-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.10: The Price of the British Pound (€/£)
</figcaption>
<div aria-describedby="fig-sinkflug-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="fig/sinkflug.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14" title="Figure&nbsp;5.10: The Price of the British Pound (€/£)"><img src="fig/sinkflug.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
<p><em>Source: Süddeutsche Zeitung am Wochenende, 17./18. November 2018, year 74, week 46, No.&nbsp;265, p.&nbsp;1 (front page).</em></p>
</div>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="sec-International-investments" class="level2 page-columns page-full" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="sec-International-investments"><span class="header-section-number">5.2</span> International investments</h2>
<p>Investing, whether through holding a currency or storing purchasing power, is inherently speculative, regardless of whether the investment is domestic or international. When you hold a foreign currency, it’s crucial to acknowledge that its value can both appreciate and depreciate. Currency values can fluctuate significantly over time due to factors such as economic policy, market sentiment, and global events. In the following sections, I will present a framework to help understand the key determinants of the rate of return on your investment. As illustrated in <a href="#fig-ai-exim" class="quarto-xref">Figure&nbsp;<span>5.11</span></a>, we will explore how a country’s interest rates, trade balances, price levels, and exchange rates are interconnected and must be analyzed together, rather than in isolation.</p>
<div id="fig-ai-exim" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-ai-exim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.11: Illustration of Interest Rate, Exchange Rate, and Trade Balance
</figcaption>
<div aria-describedby="fig-ai-exim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<p><a href="fig/ai-exim.png" class="lightbox" data-gallery="quarto-lightbox-gallery-15" title="Figure&nbsp;5.11: Illustration of Interest Rate, Exchange Rate, and Trade Balance"><img src="fig/ai-exim.png" class="img-fluid figure-img" style="width:40.0%"></a></p>
<div class="page-columns page-full"><p><em>Source: Generated using <span class="citation" data-cites="OpenAI2025Generated">OpenAI (<a href="references.html#ref-OpenAI2025Generated" role="doc-biblioref">2025</a>)</span>. </em></p><div class="no-row-height column-margin column-container"><div id="ref-OpenAI2025Generated" class="csl-entry" role="listitem">
OpenAI. (2025). <em>Generated using DALL·e</em>. <a href="https://openai.com/dall-e">https://openai.com/dall-e</a>
</div></div></div>
</div>
</figure>
</div>
<section id="foreign-exchange-reserves" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="foreign-exchange-reserves"><span class="header-section-number">5.2.1</span> Foreign exchange reserves</h3>
<p>Currencies serve as a store of value, an important function in the financial world. Foreign exchange reserves are assets held on reserve by a central bank in foreign currencies, which can include bonds, treasury bills, and other government securities. The primary purpose of holding foreign exchange reserves is to manage the exchange rate of the national currency and ensure the stability of the country’s financial system.</p>
<p>Accordingly to the <a href="https://data.imf.org/?sk=e6a5f467-c14b-4aa8-9f6d-5a09ec4e62a4"><em>Currency Composition of Official Foreign Exchange Reserves (COVER)</em></a> database of the <em>International Moentary Fund (IMF)</em>, the total foreign exchange reserves in Q3 2023 had been 11,901,53 billion U.S. Dollar. That is, $ 11,901,530,000,000!</p>
<p>The size of a country’s foreign exchange reserves can be influenced by various factors, including its balance of trade, exchange rate policies, capital flows, and the overall health of its economy. While having substantial reserves is generally seen as a sign of economic strength and stability, excessively accumulating reserves can also indicate underlying economic imbalances or protectionist policies.</p>
</section>
<section id="three-components-of-the-rate-of-return" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="three-components-of-the-rate-of-return"><span class="header-section-number">5.2.2</span> Three components of the rate of return</h3>
<p>An investment usually has different characteristics such as the default risk, opportunities, and liquidity. These characteristics and individual preferences are important to decide which investment is superior. In this course, however, we mostly refrain from discussing sophisticated features of investments here. We focus on the most important feature of an investment, that is, the rate of return. In particular, three components are important to calculate the rate of return:</p>
<section id="interest-rate" class="level4" data-number="5.2.2.1">
<h4 data-number="5.2.2.1" class="anchored" data-anchor-id="interest-rate"><span class="header-section-number">5.2.2.1</span> Interest rate</h4>
<p>The interest rate of an investment is a crucial factor that determines the return earned on invested capital over a specific period. It represents the percentage of the initial investment that is paid back to the investor as interest or profit. Formally, we can write: <span id="eq-interest"><span class="math display">\[
\underbrace{I_{t-1}}_{\text{investment in {t-1}}} \cdot\quad \underbrace{(1+i)}_{1+\text{interest rate}} = \underbrace{I_{t}}_{\text{payout amount in t}}
\tag{5.1}\]</span></span> where <span class="math inline">\(I\)</span> denotes the value of an asset measured in € in the respective time period <span class="math inline">\(t\)</span>.</p>
</section>
<section id="exchange-rate" class="level4" data-number="5.2.2.2">
<h4 data-number="5.2.2.2" class="anchored" data-anchor-id="exchange-rate"><span class="header-section-number">5.2.2.2</span> Exchange rate</h4>
<p>When investing in assets denominated in foreign currencies, investors need to convert their domestic currency into the foreign currency at the prevailing exchange rate. After the investment has been paid out in the foreign country, the investor must convert the foreign currency back to his home currency. Thus, the initial cost of the investment and the subsequent returns are influenced by the exchange rate at the beginning and the end of the investment.</p>
<p>Formally, we can write if the an investment takes in foreign country, that is, Turkey between <span class="math inline">\(t-1\)</span> and <span class="math inline">\(t\)</span>: <span id="eq-exchange"><span class="math display">\[
I^{\text{€}}_{t-1}\cdot E_{t-1}^{\frac{\text{₺}}{\text{€}}} \cdot E_{t}^{\frac{\text{€}}{\text{₺}}}= I_{t}^{\text{€}}
\tag{5.2}\]</span></span></p>
</section>
<section id="inflation" class="level4" data-number="5.2.2.3">
<h4 data-number="5.2.2.3" class="anchored" data-anchor-id="inflation"><span class="header-section-number">5.2.2.3</span> Inflation</h4>
<p>Inflation refers to the quantitative measure of the rate at which prices, represented by a basket of goods and services, increase within an economy over a specific period. Conversely, negative inflation is termed deflation. Mathematically, inflation can be defined as follows:</p>
<p><span class="math display">\[
\pi = \frac{P_t - P_{t-1}}{P_{t-1}} = \frac{P_t}{P_{t-1}} - 1
\]</span></p>
<p>Where <span class="math inline">\(\pi\)</span> represents the inflation rate and <span class="math inline">\(P_t\)</span> denotes the price at time <span class="math inline">\(t\)</span>. When inflation affects all prices, it also impacts the value of assets in which investors are invested. This relationship can be expressed as:</p>
<p><span id="eq-inflation"><span class="math display">\[
I_t = I_{t-1} \cdot (1+\pi)
\tag{5.3}\]</span></span></p>
</section>
</section>
<section id="rate-of-return-of-an-investment-abroad" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="rate-of-return-of-an-investment-abroad"><span class="header-section-number">5.2.3</span> Rate of return of an investment abroad</h3>
<p>The rate of return, <span class="math inline">\(r\)</span>, is the growth rate of an investment over time and can be described as follows: <span class="math display">\[\begin{align*}
r=&amp; \frac{I^{\text{€}}_t-I_{t-1}^{\text{€}}}{I_{t-1}^{\text{€}}}=\frac{I^{\text{€}}_t}{I^{\text{€}}_{t-1}}-1,
\end{align*}\]</span></p>
<p>Combining <a href="#eq-interest" class="quarto-xref">Equation&nbsp;<span>5.1</span></a>, <a href="#eq-exchange" class="quarto-xref">Equation&nbsp;<span>5.2</span></a>, and <a href="#eq-inflation" class="quarto-xref">Equation&nbsp;<span>5.3</span></a>, we can describe the value of our investment in period <span class="math inline">\(t\)</span> as follows: <span id="eq-Invest_t"><span class="math display">\[
I_{t}^{\text{€}}= I_{t-1}^{\text{€}} \cdot (1+i^{*}) \cdot E_{t-1}^{\frac{\text{₺}}{\text{€}}} \cdot E_{t}^{\frac{\text{€}}{\text{₺}}} \cdot  (1+\pi^{*}),
\tag{5.4}\]</span></span> where <span class="math inline">\(I_{t-1}^{\text{€}}\)</span> denotes the initial investment, <span class="math inline">\(i^{*}\)</span> denotes the interest rate abroad and <span class="math inline">\(\pi^{*}\)</span> the inflation abroad. Dividing by <span class="math inline">\(I_{t-1}^{\text{€}}\)</span> and subtracting <span class="math inline">\(1\)</span> from both sides of <a href="#eq-Invest_t" class="quarto-xref">Equation&nbsp;<span>5.4</span></a>, we see that the rate of return for an investment abroad, <span class="math inline">\(r^{*}\)</span>, has three determining factors, that are: interest rate <span class="math inline">\((1+i^*)\)</span>, inflation <span class="math inline">\((1+\pi)\)</span>, and the change of exchange rates over time <span class="math inline">\((E_{t-1}^{\frac{\text{₺}}{\text{€}}} \cdot E_{t}^{\frac{\text{€}}{\text{₺}}})\)</span>: <span class="math display">\[\begin{align*}
\underbrace{\frac{I_{t}^{\text{€}}}{I_{t-1}^{\text{€}}}-1}_r^*&amp;=
(1+i^{*})\cdot  (1+\pi^{*}) \cdot \underbrace{E_{t-1}^{\frac{\text{₺}}{\text{€}}} \cdot E_{t}^{\frac{\text{€}}{\text{₺}}}}_\alpha -1
\end{align*}\]</span> <span id="eq-ipaplus"><span class="math display">\[ r^*= (1+i^{*})\cdot  (1+\pi^{*}) \cdot \alpha -1  \tag{5.5}\]</span></span> with</p>
<ul>
<li><span class="math inline">\(\alpha=1\)</span> if the exchange rate does not change over time and<br>
</li>
<li><span class="math inline">\(\alpha&gt;1\)</span> if the home currency € depreciates or</li>
<li><span class="math inline">\(\alpha&lt;1\)</span> if the home currency € appreciates.</li>
</ul>
<p>So the exchange rate changes over time work as a third factor of your rate of return.</p>
<p>By assuming no inflation (<span class="math inline">\(\pi^{*}=0\)</span>), we can write<br>
<span id="eq-investf"><span class="math display">\[
\begin{aligned}
r^*&amp;=(1+i^{*}) \cdot \alpha -1\\
\Leftrightarrow r^*&amp;=\alpha +\alpha i^{*}  -1.
\end{aligned}
\tag{5.6}\]</span></span> Reorganizing <a href="#eq-investf" class="quarto-xref">Equation&nbsp;<span>5.6</span></a> helps to interpret it. Firstly, let us expand the right hand side of this equation adding and subtracting <span class="math inline">\(i^*\)</span> which obviously does not change the sum of the right hand side of the equation. Secondly, re-write the equation and thirdly, set <span class="math inline">\((\alpha-1)=w\)</span>: <span id="eq-rear2"><span class="math display">\[
\begin{aligned}
\Leftrightarrow r^*&amp;=\alpha +\alpha i^{*}-1+i^*-i^*\\
\Leftrightarrow r^*&amp;=\alpha-1+i^* +\alpha i^{*}-i^*\\
\Leftrightarrow r^*&amp;=\underbrace{(\alpha -1)}_w+i^* +i^{*}\underbrace{(\alpha -1)}_w\\
\Leftrightarrow r^*&amp;=w+i^* +i^{*}w
\end{aligned}
\tag{5.7}\]</span></span></p>
<p>This equation outlines the rate of return on an investment in a foreign country, influenced by two primary factors: <span class="math inline">\(i^*\)</span> and <span class="math inline">\(w\)</span>.</p>
<p>Assuming that the product <span class="math inline">\(iw\)</span> is very small, we can say that the rate of return equals approximately the interest rate plus the rate of depreciation: <span class="math display">\[r^{*}=w+i^{*}.\]</span> This approximation is often called the <em>simple rule for <span class="math inline">\(r\)</span></em>.</p>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-inveurus" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.8</strong></span> Exchange rates and where to invest</p>
<p>Suppose you want to buy a new car in Germany in one year, i.e, t=2023. Today, i.e., t=2022, you have €10,000 to invest for one year.</p>
<p>Given the following conditions:</p>
<ul>
<li>The annual interest rate in Europe is 1%.</li>
<li>The annual interest rate in the U.S.A. is 2%.</li>
<li>One US-Dollar can be converted to €0.93 this year.</li>
<li>You expect that €1 can be converted to $1.09 next year.</li>
<li>Moreover, you expect no inflation in Germany and the U.S.</li>
<li>No banking fees or alike.</li>
</ul>
<ol type="a">
<li>Calculate the return on an investment in the U.S. and Germany, respectively.</li>
<li>Do you expect the euro to appreciate or depreciate from 2022 to 2023?</li>
</ol>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Exchange rates and where to invest (<a href="#exr-inveurus" class="quarto-xref">Exercise&nbsp;<span>5.8</span></a>)</p>
<ol type="a">
<li>Rate of return in the EU is 1 percent and hence you will have 10,100 in 2023. Rate of return in the US is about 0.62 percent: <span class="math display">\[
10000\text{€} \cdot \frac{1 \$}{0.93 \text{€}}\cdot 1.02 \cdot \frac{1 \text{€}}{1.09 \$}= 10062.1485 \text{€}
\]</span> Thus, it is better to invest in Europe.</li>
<li>In 2022 you have to pay 93 Cent for a dollar and in 2023 you expect to pay about 91 Cent for a dollar. Thus, you expect the Euro to appreciate.</li>
</ol>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-invtureu" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.9</strong></span> Turkey vs.&nbsp;Germany</p>
<p>You have 100€ this year, <span class="math inline">\(t-1\)</span>, which you like to invest till next year, <span class="math inline">\(t\)</span>.</p>
<ol type="a">
<li>Where should you invest, given the following informations:
<ul>
<li>The interest rate in Germany is 1%.</li>
<li>The interest rate in Turkey is 10%.</li>
<li>1€ can be converted to 7 ₺ this year in the FOREX</li>
<li>You expect that 1 € can be converted to 7.1 ₺ next year in the FOREX.</li>
<li>You expect no inflation in Germany and Turkey.</li>
</ul></li>
<li>Calculate the exchange rate in period t that makes investing in Germany and Turkey equal profitable.</li>
<li>Explain why the Turkish Lira is under appreciation pressure in t-1.</li>
</ol>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Turkey vs.&nbsp;Germany (<a href="#exr-invtureu" class="quarto-xref">Exercise&nbsp;<span>5.9</span></a>)</p>
<ol type="a">
<li><p>When focusing solely on the interest rate, investing in Turkey appears more advantageous. However, if we consider only the development of the exchange rate, investing in Germany becomes more appealing due to the Euro appreciating relative to the Lira from period <span class="math inline">\(t-1\)</span> to <span class="math inline">\(t\)</span>. Therefore, it’s essential to calculate the return on investment to determine which of the two effects predominates. This can be done in three different ways:</p></li>
<li><p><strong>(Exact) calculation method in four steps:</strong></p>
<pre><code> 1. exchange € to ₺ in t-1:</code></pre>
<p><span class="math display">\[
100\text{€}\cdot E^{\text{₺}/\text{€}}_{t-1}= 100\text{€} \cdot 7\frac{\text{₺}}{\text{€}}=700\text{₺}
\]</span> 2. invest in either Germany or Turkey: <span class="math display">\[GER \rightarrow 100\text{€}\cdot (1+0.01)=101\text{€}\]</span> <span class="math display">\[TUR\rightarrow 700\text{₺}\cdot(1+0.1)=770\text{₺}\]</span> 3. re-exchange &nbsp;to : <span class="math display">\[770\text{₺}\cdot E^{\text{€}/\text{₺}}_{t}= 770\text{₺}\cdot\frac{1 \text{€}}{7\frac{1}{10}\text{₺}}=\frac{7700}{71}\approx 108.4507\]</span> 4. calculate the return on investment, <span class="math inline">\(r\)</span>: <span class="math display">\[\begin{align*}
r_{GER}=&amp;0.01\\
r_{TUR}=&amp;\frac{108.4507-100}{100}=0.084507
\end{align*}\]</span> <strong>Answer:</strong> The return on investment is lower in Germany. Thus, it is superior to invest the 100€ in Turkey.</p></li>
</ol>
<ol start="2" type="i">
<li><p><strong>(Exact) Calculation method in one step:</strong> <span class="math display">\[\begin{align*}
\overbrace{r}^{\text{rate of return}}=&amp; \frac{I^{\text{€}}_t-I_{t-1}^{\text{€}}}{I_{t-1}^{\text{€}}}
\end{align*}\]</span> with <span class="math inline">\(I^{\text{€}}_{t}=\overbrace{I^{\text{€}}_{t-1}}^{\text{investment in t-1}}\cdot \overbrace{E^{\text{₺}/\text{€}}_{t-1}}^{\text{exchange rate in t-1}}\cdot \overbrace{(1+i)}^{1+ \text{interest rate}}\cdot \overbrace{E^{\text{€}/\text{₺}}_{t}}^{\text{exchange rate in t}}\)</span> <span class="math display">\[\begin{align*}
TUR\rightarrow I_{t}^{\text{€}}=&amp;100\text{€}\cdot 7\frac{\text{₺}}{\text{€}}\cdot (1+0.1)\cdot\frac{1\text{€}}{7.1\text{₺}}=108.4507 \rightarrow r_{TUR}=0.084507\\
GER\rightarrow I_{t}^{\text{€}}=&amp; 100\text{€} \cdot 1 \cdot (1+0.01)\cdot 1 = 101\text{€}\rightarrow r_{GER}=0.01
\end{align*}\]</span></p></li>
<li><p><strong>(Approximative) calculation method:</strong> Steps a) to c) can be summarized as two rates of changes: <span class="math display">\[\begin{align*}
\underbrace{r'}_{\text{approximative rate of return}}=&amp;\underbrace{i}_{\text{interest rate}}+\underbrace{w}_{\text{rate of depreciation}}\\
       \text{with}\quad    w=&amp;\frac{E^{\text{€}/\text{₺}}_{t}}{E^{\text{€}/\text{₺}}_{t-1}}-1
\end{align*}\]</span> <span class="math display">\[\begin{align*}
       r'_{GER}=&amp;0.01\\
       r'_{TUR}=&amp;0.1+\frac{\frac{10}{71}}{\frac{10}{70}}-1=0.1+\frac{700}{710}-1=0.1-\frac{10}{710}=\frac{61}{710}\approx 0.08591
\end{align*}\]</span></p></li>
</ol>
<ol start="2" type="a">
<li>Both investments are equal profitable if <span class="math display">\[r_{GER}=r_{TUR}.\]</span> Given the information in period <span class="math inline">\(t-1\)</span>, the exact exchange rate in period <span class="math inline">\(t\)</span> that makes investments are equal profitable, <span class="math inline">\(E^{\text{€}/\text{₺}*}_{t}\)</span>, is calculated as follows: <span class="math display">\[\begin{align*}
          I^{\text{€}}_{t}&amp;=I^{\text{€}}_{t-1} E^{\text{₺}/\text{€}}_{t-1} (1+i) E^{\text{€}/\text{₺} *}_{t}\\
          \Leftrightarrow E^{\text{€}/\text{₺}*}_{t}&amp;= \frac{I^{\text{€}}_{t}}{(I^{\text{€}}_{t-1} E^{\text{₺}/\text{€}}_{t-1} (1+i))}=\frac{101}{(100\cdot 7 \cdot 1.1)}=\frac{101}{770}\approx 0.1311
\end{align*}\]</span></li>
</ol>
<p>The approximate exchange rate in period <span class="math inline">\(t\)</span> that makes investments are equal profitable, <span class="math inline">\(E^{\text{€}/\text{₺}*'}_{t}\)</span>, is calculated as follows: <span class="math display">\[\begin{align*}
r_{GER}=&amp;i_{TUR}+\frac{E^{\text{€}/\text{₺}*'}_{t}}{E^{\text{€}/\text{₺}}_{t-1}}-1\\
            \Leftrightarrow r_{GER}-i_{TUR}+1=&amp;\frac{E^{\text{€}/\text{₺}*'}_{t}}{E^{\text{€}/\text{₺}}_{t-1}}\\
\Leftrightarrow E^{\text{€}/\text{₺}*'}_{t}=&amp; (r_{GER}-i_{TUR}+1)\cdot E^{\text{€}/\text{₺}}_{t-1}\\
            \Leftrightarrow E^{\text{€}/\text{₺}*'}_{t}=&amp; (0.01-0.1+1)\cdot \frac{1}{7}=\frac{91}{100}\cdot \frac{1}{7}=\frac{91}{700}=0.13
\end{align*}\]</span> Let us proof our results by re-calculating the rate of return for an investment in Turkey with <span class="math inline">\(E^{\text{€}/\text{₺}*}_{t}\)</span> and <span class="math inline">\(E^{\text{€}/\text{₺}*'}_{t}\)</span>: <span class="math display">\[\begin{align*}
            r'_{TUR}=&amp;0.1+\frac{\frac{91}{700}}{\frac{1}{7}}-1=\frac{637}{700}-0.9=0.01\\
            I_{t}^{\text{€}*}=&amp;100\text{€}\cdot 7\frac{\text{₺}}{\text{€}}\cdot (1+0.1)\cdot \frac{91}{700}\frac{\text{€}}{\text{₺}}= \frac{70070}{700}=100.1\\
            \rightarrow r_{TUR}^*=&amp;0.01
\end{align*}\]</span></p>
<ol start="3" type="a">
<li>The ₺ must appreciate in t-1 since it is more profitable to exchange € to store the asset value in Turkey. That means the demand curve in the FOREX shifts upwards till the exchange rate equals the exchange rate that makes both investments equal profitable and hence nobody has an incentive to demand more ₺ for the given exchange rate <span class="math inline">\(E^{\text{€}/\text{₺}*}_{t}\)</span> as calculated above.</li>
</ol>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-inrinvest" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.10</strong></span> Suppose you have 50,000 Indian Rupees (INR) this year that you want to invest for one year from <span class="math inline">\(t\)</span> to <span class="math inline">\(t+1\)</span> and then buy something with the Indian Rupees in India. Calculate the return on an investment in India and Germany, given the following conditions:</p>
<ul>
<li>The annual interest rate in India is 5% and 2% in Germany.</li>
<li>1 INR can be converted to 0.01 Euro (EUR) this year, <span class="math inline">\(t\)</span>.<br>
</li>
<li>You expect the Indian Rupee to depreciate, that is, you expect 1 EUR to cost 1 INR more next year, that is <span class="math inline">\(t+1\)</span>.</li>
<li>Moreover, you expect no inflation in India and Germany.</li>
</ul>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The return on investment for the investment in India is 5%.</p>
<p>The return on investment for the investment in Germany can be calculated as follows: <span class="math display">\[
50,000 \ \text{INR} \cdot \underbrace{\frac{0.01 \text{EUR}}{1 \ \text{INR}}}_{= \frac{100 \ \text{INR}}{1 \ \text{EUR}}} \cdot 1.02 \cdot  \frac{101 \ \text{INR}}{1 \ \text{EUR}}  = 51,510  \ \text{INR}
\]</span> To calculate the rate of return calculate <span class="math display">\[
\frac{51,510-50,000}{50,000}\cdot 100=3.02.
\]</span> Thus, the return on investment for the investment in Germany is 3.02%. One challenge of this exercise is to consider “1 EUR to cost 1 INR more” properly. This does not mean 1 INR is equal to 1 €!</p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-inparcon" class="level3" data-number="5.2.4">
<h3 data-number="5.2.4" class="anchored" data-anchor-id="sec-inparcon"><span class="header-section-number">5.2.4</span> The interest parity condition</h3>
<p>Assume the rate of return is lower domestically than it is for investments abroad. Representing the foreign country with an asterisk <span class="math inline">\((*)\)</span>, this situation, where investing money abroad is more profitable, can be expressed as:</p>
<p><span class="math display">\[\begin{align*}
r&amp;&lt;r^{*}.
\end{align*}\]</span> Given that domestically the rate of return, <span class="math inline">\(r\)</span>, equals the interest rate, <span class="math inline">\(i\)</span>, assuming zero inflation, and that the simple rule for an investment abroad is described by <span class="math inline">\(r^{*} = w + i^{*}\)</span>, we can rewrite the equation as: <span class="math display">\[
i&lt; w+i^{*}.
\]</span> What would happen if financial market actors became aware of this?</p>
<p>Market participants would likely convert their domestic currency into the foreign currency to invest abroad, increasing demand for the foreign currency. Consequently, the foreign currency would appreciate, becoming relatively more expensive. This implies that <span class="math inline">\(w\)</span> is negative. This appreciation process halts when investing abroad no longer offers a higher return. If the attractiveness of investments is equalized, the FOREX is in equilibrium. The deposits of all currencies offer the same expected rate of return. In other words, in equilibrium the exchange rate, <span class="math inline">\(w\)</span>, assures that the rate of return from the home country, <span class="math inline">\(r\)</span>, is equal to the rate of return in any foreign country, denoted with an asterisk (<span class="math inline">\(*\)</span>):</p>
<p><span class="math display">\[\begin{align}
  r&amp;=r^{*}\\
  i&amp;= w + i^{*}\\
\end{align}\]</span> <span id="eq-ipa"><span class="math display">\[ \Leftrightarrow w= i-i^{*} \tag{5.8}\]</span></span></p>
<p>The interest parity condition (<a href="#eq-ipa" class="quarto-xref">Equation&nbsp;<span>5.8</span></a>) enables us to analyze how variations in interest rates and expected exchange rates affect current exchange rates through comparative static analysis of the equation: <span class="math display">\[
\frac{\partial w}{\partial i} &gt; 0; \quad \frac{\partial w}{\partial i^*} &lt; 0.
\]</span> This means:</p>
<ul>
<li>An increase in the domestic interest rate results in a positive change in the depreciation rate, leading to the depreciation of the domestic currency.</li>
<li>An increase in the foreign interest rate causes a negative change in the depreciation rate, resulting in the appreciation of the domestic currency.</li>
</ul>
</section>
<section id="the-theory-in-real-markets-unpegging-the-swiss-franc" class="level3" data-number="5.2.5">
<h3 data-number="5.2.5" class="anchored" data-anchor-id="the-theory-in-real-markets-unpegging-the-swiss-franc"><span class="header-section-number">5.2.5</span> The theory in real markets: Unpegging the Swiss Franc</h3>
<p>You might now question whether this theory of the interest parity condition truly holds in real-world markets. Analyzing international markets and the FOREX empirically is challenging due to the frequent occurrence of both large and small exogenous shocks on a global scale, each impacting market outcomes in various ways. Furthermore, market dynamics are often influenced by emotions and speculation rather than solely measurable facts. However, there are instances where the shocks are so significant that the fundamental forces driving the market become visible, even without a sophisticated empirical identification strategy that controls for confounding effects. The case study of the unexpected unpegging of the Swiss Franc serves as a poignant example. It vividly demonstrates that the principles underpinning the interest parity condition are not merely theoretical constructs but actively influence real market behaviors.</p>
<p>Until early 2015, the Swiss National Bank (SNB) had a policy goal to maintain the franc above the cap of 1.20 Francs per Euro, aiming to protect exporters and combat deflationary pressures. However, in a surprising move, the SNB unpegged the Franc in 2015. This decision was influenced by the appreciation pressure on the Franc, as many investors many investors wanted to store their assets in the Swiss Franc. Following the SNB’s announcement, the exchange rate plunged from 1.20 to 1.00 Franc per Euro <span class="math inline">\((E^{\frac{CHF}{\text{€}}})\)</span>, as illustrated in <a href="#fig-franc" class="quarto-xref">Figure&nbsp;<span>5.12 (a)</span></a> Almost simultaneously, the interest rate experienced a decline, as depicted in <a href="#fig-swiss" class="quarto-xref">Figure&nbsp;<span>5.12 (b)</span></a>. These developments align precisely with what the interest parity condition would predict, demonstrating its applicability in real-world financial market dynamics.</p>
<div id="fig-snb" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-snb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.12: The impact of unpegging the Franc on capital markets
</figcaption>
<div aria-describedby="fig-snb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-snb" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-franc" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-fig" id="fig-franc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) The exchange rate: <span class="math inline">\(E^{\frac{CHF}{\text{€}}}\)</span>
</figcaption>
<div aria-describedby="fig-franc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="fig/franc_euro.png" class="lightbox" data-gallery="fig-snb" title="Figure&nbsp;5.12&nbsp;(a): The exchange rate: E^{\frac{CHF}{\text{€}}}"><img src="fig/franc_euro.png" class="img-fluid figure-img" data-ref-parent="fig-snb"></a>
</div>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-snb" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-swiss" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-fig" id="fig-swiss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Interest rate for investments in Switzerland
</figcaption>
<div aria-describedby="fig-swiss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="fig/swiss_i.png" class="lightbox" data-gallery="fig-snb" title="Figure&nbsp;5.12&nbsp;(b): Interest rate for investments in Switzerland"><img src="fig/swiss_i.png" class="img-fluid figure-img" data-ref-parent="fig-snb"></a>
</div>
</figure>
</div>
</div>
</div>
</div>
</figure>
</div>
<p>To analyze the relationship between changes in exchange rates and interest rates, we need to consider the interest parity assumption of <a href="#eq-ipa" class="quarto-xref">Equation&nbsp;<span>5.8</span></a>: <span class="math display">\[
w= i-i^{*}
\]</span> where <span class="math display">\[w=\frac{E_{t}^{\frac{\text{€}}{CHF}}}{E_{t-1}^{\frac{\text{€}}{CHF}}}-1.\]</span> In January 2015, the exchange rate <span class="math inline">\(E^{\frac{CHF}{\text{€}}}\)</span> decreased from 1.20 to 1.00. Alternatively, we can express this change in direct quotation, noting that the exchange rate <span class="math inline">\(E^{\frac{\text{€}}{CHF}}\)</span> increased from <span class="math inline">\(E^{\frac{\text{€}}{CHF}}_{t-1}\approx \frac{1}{1.20}\approx 0.83\)</span> to <span class="math inline">\(E^{\frac{\text{€}}{CHF}}_{t}\approx 1.00\)</span>, resulting in <span class="math display">\[
  w=\frac{E_{t}^{\frac{\text{€}}{CHF}}}{E_{t-1}^{\frac{\text{€}}{CHF}}}-1=\frac{1}{0.83}-1=0.20.
\]</span></p>
<p>Since <span class="math inline">\(w &gt; 0\)</span>, the fraction on the left-hand side of the interest rate parity equation must also be positive, as already mentioned. This implies that <span class="math display">\[i - i^* &gt; 0,\]</span> which means that an interest rate spread must occur. This condition can occur if the foreign interest rate <span class="math inline">\(i^*\)</span> decreases or the domestic interest rate <span class="math inline">\(i\)</span> increases. In our observations, we can indeed see a pattern that is consistent with our theoretical expectations.</p>
<p>It is important to acknowledge that our theoretical framework simplifies the complex interplay of factors that influence both exchange rates and interest rates. Despite this simplification, the model highlights the key forces driving market dynamics. However, it is important to point out that the actual numbers may not perfectly match our theoretical predictions in quantitative terms, as shown in Figure <a href="#fig-chg_sti" class="quarto-xref">Figure&nbsp;<span>5.13</span></a>.</p>
<div id="fig-chg_sti" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-chg_sti-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.13: Short-term interest rates across Germany and Switzerland over time
</figcaption>
<div aria-describedby="fig-chg_sti-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="fig/chg_sti.png" class="lightbox" data-gallery="quarto-lightbox-gallery-18" title="Figure&nbsp;5.13: Short-term interest rates across Germany and Switzerland over time"><img src="fig/chg_sti.png" class="img-fluid figure-img" style="width:60.0%"></a></p>
<p><em>Source: Data are taken from the OECD and show the total, % per annum.</em></p>
</div>
</figure>
</div>
</section>
<section id="the-fisher-effect" class="level3 page-columns page-full" data-number="5.2.6">
<h3 data-number="5.2.6" class="anchored" data-anchor-id="the-fisher-effect"><span class="header-section-number">5.2.6</span> The Fisher Effect</h3>
<p>The <em>Fisher Effect</em> is an economic theory proposed by economist Irving Fisher (1867-1947), which describes the relationship between (expected) inflation and both nominal and real interest rates.</p>
<p>According to the <em>Fisher Effect</em>, the nominal interest rate is equal to the sum of the real interest rate and the (expected) inflation rate. In formula terms, it is often expressed as: <span id="eq-fie"><span class="math display">\[
r=i+\pi.
\tag{5.9}\]</span></span></p>
<p>We can derive <a href="#eq-fie" class="quarto-xref">Equation&nbsp;<span>5.9</span></a> assuming that the exchange rate is stable over time <span class="math display">\[
\left( E_{t-1}^{\frac{\text{€}}{\text{₺}}} =E_{t}^{\frac{\text{€}}{\text{₺}}} \Leftrightarrow
\frac{E_{t-1}^{\frac{\text{€}}{\text{₺}}}}{E_{t}^{\frac{\text{€}}{\text{₺}}}}=1 \Leftrightarrow \alpha=1 \right)
\]</span> and using this in <a href="#eq-ipaplus" class="quarto-xref">Equation&nbsp;<span>5.5</span></a>, we get: <span class="math display">\[\begin{align}
r^*&amp;= (1+i^{*})\cdot  (1+\pi^{*}) \cdot \underbrace{\alpha}_{=1} -1  \\
\Leftrightarrow r=&amp;  i+ \pi+ \pi i
\end{align}\]</span> Assuming that the product <span class="math inline">\(\pi i\)</span> is very small, we can say that the rate of return equals approximately the interest rate plus the inflation rate. This approximation shown in <a href="#eq-fie" class="quarto-xref">Equation&nbsp;<span>5.9</span></a> is often called the <em>Fisher Effect</em>.</p>
<p>Considering now cross-country differences in their rate of return, we can explain the rate of return spread by the inflation rate and the nominal interest rate spread as follows: <span id="eq-fie2"><span class="math display">\[r_{GER}-r_{TUR}= \pi_{GER}-\pi_{TUR} + i_{GER}-i_{TUR}. \tag{5.10}\]</span></span></p>
<p>We have learned in <a href="#sec-inparcon" class="quarto-xref"><span>Section 5.2.4</span></a> (the interest parity condition) that the rate of return can differ only in the short run and will be equal across countries in the long run (<span class="math inline">\(r_{GER} - r_{TUR} = 0\)</span>). Utilizing this concept in <a href="#eq-fie" class="quarto-xref">Equation&nbsp;<span>5.9</span></a>, we can demonstrate that the nominal interest rates of countries will adjust to accommodate any changes in (expected) inflation, and vice versa:</p>
<p><span class="math display">\[i_{GER} - i_{TUR} = \pi_{GER} - \pi_{TUR}.\]</span></p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Recommended reading">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Recommended reading
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="citation" data-cites="Wikipedia2025Fisher">Wikipedia (<a href="references.html#ref-Wikipedia2025Fisher" role="doc-biblioref">2025</a>)</span>: <a href="https://en.wikipedia.org/wiki/Fisher_effect">Wikipedia entry to the Fisher Effect</a>.</p>
</div>
</div>
<div class="no-row-height column-margin column-container"><div id="ref-Wikipedia2025Fisher" class="csl-entry" role="listitem">
Wikipedia. (2025). <em>Fisher effect</em>. <a href="https://en.wikipedia.org/wiki/Fisher_effect">https://en.wikipedia.org/wiki/Fisher_effect</a>
</div></div></section>
</section>
<section id="sec-bofpayments" class="level2 page-columns page-full" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="sec-bofpayments"><span class="header-section-number">5.3</span> Balance of payments</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Required reading">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Required reading
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="citation" data-cites="CEA2004Economic">Council of Economic Advisers (<a href="references.html#ref-CEA2004Economic" role="doc-biblioref">2004</a>, ch.&nbsp;14)</span></p>
</div>
</div>
<div class="no-row-height column-margin column-container"><div id="ref-CEA2004Economic" class="csl-entry" role="listitem">
Council of Economic Advisers. (2004). <em>Economic report of the president: Transmitted to the congress february 2004</em> (N. G. Mankiw, K. J. Forbes, &amp; H. S. Rosen, Eds.). <span>U.S.</span> Government Printing Office. <a href="https://www.presidency.ucsb.edu/sites/default/files/books/presidential-documents-archive-guidebook/the-economic-report-of-the-president-truman-1947-obama-2017/2004.pdf">https://www.presidency.ucsb.edu/sites/default/files/books/presidential-documents-archive-guidebook/the-economic-report-of-the-president-truman-1947-obama-2017/2004.pdf</a>
</div></div><section id="introduction" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">5.3.1</span> Introduction</h3>
<p>The <em>Balance of Payments</em> is a record of a country’s financial transactions with the rest of the world. It tracks the money flowing in and out through various economic activities. If we account for all transactions, the inflow and outflow should theoretically balance. Before I elaborate on this concept, let’s clarify some key terms:</p>
<ul>
<li><em>Exports</em>: Goods and services sold to other countries.</li>
<li><em>Imports</em>: Goods and services bought from other countries.</li>
<li><em>Trade balance</em>: The difference between the value of goods and services a country sells abroad and those it buys from abroad, also known as <em>net exports</em>.</li>
<li><em>Trade surplus</em>: When a country sells more than it buys, resulting in a positive trade balance.</li>
<li><em>Trade deficit</em>: When a country buys more than it sells, leading to a negative trade balance.</li>
<li><em>Balanced trade</em>: When the value of exports equals imports.</li>
<li><em>Net capital outflow</em>: The difference between the purchase of foreign assets by domestic residents and the purchase of domestic assets by foreigners. This equals net exports, indicating that a country’s savings can fund investments domestically or abroad. We will elaborate on that later on in greater detail.</li>
</ul>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-factsfortrade" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.11</strong></span> Some facts about foreign trade</p>
<p>Make yourself familiar with the descriptive statistics at <a href="https://www.destatis.de/EN/Themes/Economy/Globalisation-Indicators/foreign-trade.html?nn=22760">destatis.de</a>, the World Trade Organization <a href="https://www.wto.org/english/res_e/statis_e/statis_maps_e.htm">here</a> and <a href="https://www.wto.org/english/res_e/statis_e/statis_e.htm">here</a>, the <a href="https://data.oecd.org/trade/trade-in-goods-and-services.htm">OECD</a>, and <a href="https://cepr.org/voxeu/columns/world-trade-historical-database">World Trade Historical Database</a> by the CEPR.</p>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-factsfortrade" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.12</strong></span> <a href="#fig-balance" class="quarto-xref">Figure&nbsp;<span>5.14</span></a> represents the foreign investment surplus and the trade deficit. Discuss why the two lines mirror each other. Could this be a coincidence?</p>
<div id="fig-balance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-balance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.14: U.S. Balance of Payments
</figcaption>
<div aria-describedby="fig-balance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="fig/balance.png" class="lightbox" data-gallery="quarto-lightbox-gallery-19" title="Figure&nbsp;5.14: U.S. Balance of Payments"><img src="fig/balance.png" class="img-fluid figure-img" style="width:90.0%"></a>
</div>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="the-payments-must-be-balanced" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="the-payments-must-be-balanced"><span class="header-section-number">5.3.2</span> The payments must be balanced!</h3>
<p>Every international financial transaction is essentially an exchange. When a country sells goods or services, the buying country compensates by transferring assets. Consequently, the total value of goods and services a country sells (its net exports) must be equal to the value of assets it acquires (its net capital outflow).</p>
<p>The <em>Balance of Payments</em> account consists of two primary components:</p>
<ol type="1">
<li><p>The <strong>Current account</strong> (Leistungsbilanz) measures a country’s trade balance (goods and services exports minus imports) plus the effects of net income and direct payments. It is positive, if a country is a net lender to the rest of the world and negative, if it is a net borrower from the rest of the world. In other words, an account surplus increases a country’s net foreign assets.</p></li>
<li><p>The <strong>Capital account</strong> (Kapitalbilanz) reflects the net change in ownership of national assets. Capital can flow in the form of following:</p>
<ol type="1">
<li><strong>Foreign Direct Investment (FDI)</strong>: It involves investing in foreign companies with the intention of controlling or significantly influencing their operations.</li>
<li><strong>Foreign Portfolio Investment (FPI)</strong>: This type of investment is in foreign financial assets, such as stocks and bonds, where the investor does not seek control over the companies.</li>
<li><strong>Other investments</strong>: This includes capital flows into bank accounts or funds provided as loans. It also encompasses the reserve account, which is managed by the central bank responsible for buying and selling foreign currencies.</li>
</ol></li>
</ol>
<p>Ignoring statistical effects, these two subaccounts must sum to zero.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Imagine Boeing, an American company, sells airplanes to a Japanese airline:</p>
<ol type="1">
<li>Boeing transfers airplanes to the Japanese firm, and in return, the Japanese firm pays Boeing in Yen. This transaction increases exports (boosting net exports) and results in the United States acquiring foreign assets in the form of Yen (increasing net capital outflow).</li>
<li>Boeing might then convert its Yen to U.S. Dollars through a financial exchange. For example, if an American mutual fund wants to invest in a Japanese company, Boeing’s sale of planes (a net export) is mirrored by the mutual fund’s investment in Japan (a net capital outflow).</li>
<li>Alternatively, Boeing could exchange its Yen with an American company looking to purchase goods or services from Japan. In this scenario, the value of imports matches the value of exports, leaving net exports unchanged.</li>
</ol>
</div>
</div>
<p>While it’s true that the overall totals of payments and receipts must inherently balance, certain transaction types can create imbalances, leading to either deficits or surpluses. These imbalances may manifest in various sectors such as trade in goods (commodities), services trade, foreign investment income, unilateral transfers (including foreign aid), private investment, and the flow of gold and currency between central banks and treasuries, among other international dealings. It’s crucial to note, though, that the accounting framework ensures these surpluses and deficits ultimately zero out, adhering to the principles of double-entry bookkeeping.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Take, for example, a scenario where Americans purchase cars from Germany without engaging in any other transactions with it. The outcome is that Germans accumulate dollars, which can be maintained as bank deposits in the United States or within other U.S.-based assets. The American payment for German automobiles is counterbalanced by German acquisitions of dollar assets, including investments in U.S. entities and institutions. This exchange means Germany sells cars to the U.S., while the U.S. sells dollars or dollar-backed assets to Germany. Consequently, Germany experiences a trade surplus, indicated by a positive trade balance and a corresponding surplus in its current account, which encompasses the trade balance. Nonetheless, this also implies Germany faces a deficit in its capital account, characterized by a net outflow of money.</p>
</div>
</div>
<p><a href="#tbl-hypoaccount" class="quarto-xref">Table&nbsp;<span>5.5</span></a></p>
<div id="tbl-hypoaccount" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-hypoaccount-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.5: A hypothetical account
</figcaption>
<div aria-describedby="tbl-hypoaccount-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 4%">
<col style="width: 44%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th>Receipt (credit)</th>
<th></th>
<th>Payments (debits)</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Current Account</strong></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>1. Export of goods and services</td>
<td>800</td>
<td>3. Import of goods and services</td>
<td>600</td>
</tr>
<tr class="odd">
<td>2. Unilateral receipts</td>
<td>300</td>
<td>4. Unilateral payments</td>
<td>390</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td><strong>1100</strong></td>
<td><strong>Total</strong></td>
<td><strong>990</strong></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><strong>Capital Account</strong></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>5. Borrowings</td>
<td>700</td>
<td>7. Lendings</td>
<td>750</td>
</tr>
<tr class="even">
<td>6. Sale of gold/assets</td>
<td>100</td>
<td>8. Purchase of gold/assets</td>
<td>150</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>800</td>
<td><strong>Total</strong></td>
<td>900</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>Errors and omissions</td>
<td>10</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>1900</td>
<td><strong>Total</strong></td>
<td>1900</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="a-normative-discussion-of-imbalances-in-the-capital-and-current-account" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="a-normative-discussion-of-imbalances-in-the-capital-and-current-account"><span class="header-section-number">5.3.3</span> A normative discussion of imbalances in the capital and current account</h3>
<p>Normatively discussing imbalances in the capital and current accounts of countries involves evaluating these phenomena from a perspective of what ought to be, considering ethical, practical, and policy implications. These imbalances are not merely numerical figures; they reflect underlying economic activities and policy decisions with significant implications for national and global economic health.</p>
<section id="current-account-imbalances" class="level4" data-number="5.3.3.1">
<h4 data-number="5.3.3.1" class="anchored" data-anchor-id="current-account-imbalances"><span class="header-section-number">5.3.3.1</span> Current account imbalances</h4>
<p>The current account includes trade in goods and services. A surplus in the current account indicates that a country is exporting more goods than it imports.</p>
<p><strong>Surpluses:</strong> Normatively, persistent current account surpluses might be viewed as a sign of a country’s competitive strength in the global market. However, they can also indicate underconsumption or insufficient domestic investment, suggesting that a country is not fully utilizing its economic resources to improve the living standards of its population. Furthermore, large surpluses can lead to tensions with trading partners and might prompt accusations of unfair trade practices or currency manipulation.</p>
<p><strong>Deficits:</strong> On the other hand, persistent deficits could signal domestic economic vitality and an attractive environment for investment, reflecting high consumer demand and robust growth. Yet, they can also indicate structural problems, such as a lack of competitiveness, reliance on foreign borrowing to sustain consumption, or inadequate savings rates. Over time, large deficits may lead to unsustainable debt levels, making the country vulnerable to financial crises.</p>
</section>
<section id="capital-account-imbalances" class="level4" data-number="5.3.3.2">
<h4 data-number="5.3.3.2" class="anchored" data-anchor-id="capital-account-imbalances"><span class="header-section-number">5.3.3.2</span> Capital account imbalances</h4>
<p>The capital account records the net change in ownership of national assets. It includes the flow of capital into and out of a country, such as investments in real estate, stocks, bonds, and government debt.</p>
<p><strong>Inflows:</strong> Capital account inflows can signify strong investor confidence in a country’s economic prospects, potentially leading to increased investment and growth. However, excessive short-term speculative inflows can destabilize the economy, leading to asset bubbles and subsequent financial crises when the capital is suddenly withdrawn.</p>
<p><strong>Outflows:</strong> Capital outflows might indicate a lack of confidence in the domestic economy or better opportunities abroad. While some level of outflow is normal for diversified investment portfolios, large and rapid outflows can precipitate a financial crisis by depleting foreign reserves and putting downward pressure on the currency.</p>
</section>
</section>
<section id="a-formal-representation" class="level3" data-number="5.3.4">
<h3 data-number="5.3.4" class="anchored" data-anchor-id="a-formal-representation"><span class="header-section-number">5.3.4</span> A formal representation</h3>
<p>In the following, I present a streamlined perspective on the global trading system. This overview does not engage with the benefits or drawbacks of maintaining trade surpluses or deficits, a subject that warrants its own discussion. However, it aims to identify the factors influencing current account deficits and surpluses.</p>
<section id="closed-economy" class="level4" data-number="5.3.4.1">
<h4 data-number="5.3.4.1" class="anchored" data-anchor-id="closed-economy"><span class="header-section-number">5.3.4.1</span> Closed economy</h4>
<p>Within a closed economy, we identify three principal actors: households, firms, and the government. Let’s define <span class="math inline">\(C\)</span> as the consumption of goods and services by households, encompassing necessities and luxuries like food, housing, and entertainment. Let <span class="math inline">\(G\)</span> represent government expenditures, which cover infrastructure, social services, military outlays, education, and more. Lastly, <span class="math inline">\(I\)</span> symbolizes the investment by firms in assets such as machinery, buildings, and research and development. Given these components, the total economic output, <span class="math inline">\(Y\)</span>, can be expressed by the <em>fundamental equation of economics</em> as:</p>
<p><span class="math display">\[
Y = C + I + G.
\]</span></p>
<p>This equation encapsulates the aggregate spending within a closed economy, highlighting the interplay between consumption, investment, and government expenditure in determining overall economic activity.</p>
<p>If we define national savings, <span class="math inline">\(S\)</span>, as the share of output not spent on household consumption or government purchases, then the investments, <span class="math inline">\(I\)</span>, must be equal to the savings in a closed economy: <span class="math display">\[\begin{align*}
Y &amp;= C + I + G\\
\Leftrightarrow \underbrace{Y - C - G}_S &amp;= I \\
\Leftrightarrow S &amp;= I,
\end{align*}\]</span></p>
<p>This implies that within a closed economy, any portion of the output that is not consumed—either privately by households (<span class="math inline">\(C\)</span>) or by the government (<span class="math inline">\(G\)</span>)—necessarily must be allocated towards investment (<span class="math inline">\(I\)</span>). Thus, the equation underscores a foundational economic principle: the total output of an economy (<span class="math inline">\(Y\)</span>) is either consumed or invested, leaving no surplus output.</p>
</section>
<section id="open-economy" class="level4" data-number="5.3.4.2">
<h4 data-number="5.3.4.2" class="anchored" data-anchor-id="open-economy"><span class="header-section-number">5.3.4.2</span> Open economy</h4>
<p>In an open economy, the dynamics of household consumption, government expenditures, and firm investments extend beyond domestic production to include imports from and exports to foreign markets. Thus, an economy can import and export goods. Denoting imports by <span class="math inline">\(IM\)</span> and exports by <span class="math inline">\(EX\)</span>, we can re-write the fundamental equation of economics by adding the concept of net exports (<span class="math inline">\(NEX\)</span>), the difference between a country’s exports and imports. A positive net export value (<span class="math inline">\(EX &gt; IM\)</span>) indicates a trade surplus, reflecting that the economy exports more than it imports. Conversely, a negative net export value (<span class="math inline">\(EX &lt; IM\)</span>) signifies a trade deficit, where imports exceed exports:</p>
<p><span class="math display">\[\begin{align*}
Y &amp;= C + I + G + \underbrace{EX - IM}_{NEX}\\
\Leftrightarrow \underbrace{Y - C - G}_S &amp;= I + NEX\\
\Leftrightarrow \underbrace{S-I}_{NCO} &amp;= NEX
\end{align*}\]</span></p>
<p>In scenarios where investment equals savings (<span class="math inline">\(I = S\)</span>), the economy’s net exports are zero, reflecting a balance between domestic production not allocated towards household or government consumption and investments. However, when an economy experiences a trade surplus (<span class="math inline">\(NEX &gt; 0\)</span>), such as Germany in recent decades, it implies that domestic savings exceed investments. This surplus indicates that the country produces more than it spends on domestic goods and services, channeling excess savings into investments abroad. Thus, savings not utilized domestically (<span class="math inline">\(S - I\)</span>) are equivalent to the net capital outflow (<span class="math inline">\(NCO\)</span>), establishing a direct link between a country’s trade surplus and its role as a global lender or investor:</p>
<p><span class="math display">\[
NCO = NEX
\]</span></p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Net exports must be equal to net capital outflow</p>
<p>The accounting identities above simply state that there is a <em>balance of payments</em>. The Balance of Payment accounts are based on double-entry bookkeeping and hence the annual account has to be balanced. If an economy has a current account trade deficit (surplus), it is offset one-to-one by a capital account surplus (deficit) to assure a balance of payments. In other words, if an economy wants to import more goods than it produces, it must attract foreign capital to be invested at home.</p>
</div>
</div>
</div>
</section>
</section>
<section id="case-study-u.s.-trade-deficit" class="level3" data-number="5.3.5">
<h3 data-number="5.3.5" class="anchored" data-anchor-id="case-study-u.s.-trade-deficit"><span class="header-section-number">5.3.5</span> Case study: U.S. trade deficit</h3>
<p>Consider a scenario where the United States is unable to attract sufficient capital flows from abroad to finance its trade deficit. In such a case, American consumers continue purchasing foreign goods with US Dollars, leading to an outflow of US Dollars that surpasses inflow. This imbalance results in an increased supply of US Dollars relative to its demand, causing the value of the US Dollar to depreciate. A depreciated US Dollar would, in theory, make US exports more competitive (cheaper for foreign buyers) and imports more costly, thereby potentially reducing the current account deficit. However, the trade deficit of the United States has remained relatively stable, and the US Dollar has not experienced significant depreciation. This stability is partly why former President Trump criticized other countries for allegedly <em>manipulating</em> their currencies, see <a href="#fig-mainpul" class="quarto-xref">Figure&nbsp;<span>5.15</span></a>.</p>
<p>Trump’s stance on the trade deficit was clear: he perceived it as detrimental to the United States. He advocated for a weaker dollar and lower interest rates to address this issue. A weaker dollar would render American products more affordable internationally, stimulating exports and discouraging imports. Concurrently, lower interest rates in the United States would diminish the country’s appeal for foreign capital investments (<span class="math inline">\(I\)</span> would decrease), leading to reduced net capital inflows. This adjustment would, in turn, decrease the <strong>Capital Account</strong> surplus and, by extension, shrink the <strong>Current Account</strong> deficit. Specifically, Trump accused the Chinese government and the European Central Bank of implementing policies that undervalue their currencies (the Renminbi and the Euro), thereby gaining an unfair advantage in trade.</p>
<div id="fig-mainpul" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-mainpul-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.15: Trump worries about the U.S. trade deficit
</figcaption>
<div aria-describedby="fig-mainpul-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="fig/manipul.png" class="lightbox" data-gallery="quarto-lightbox-gallery-20" title="Figure&nbsp;5.15: Trump worries about the U.S. trade deficit"><img src="fig/manipul.png" class="img-fluid figure-img" style="width:70.0%"></a>
</div>
</figure>
</div>
<p>As Trump thinks a trade deficit is bad for the United States, he would like to have a weak dollar and low interest rates. A weak dollar makes American products cheap for the rest of the world and has positive effects on exports and negative on imports. A low interest rate in the United States would make the country less attractive for foreign capital investments (<span class="math inline">\(I\)</span> would become smaller), meaning the net capital inflows would decrease and so would the <strong>Capital Account</strong>’s surplus (and with it, the <strong>Current Account</strong> deficit would become smaller). In concrete terms, he claims that in particular the Chinese government and the European Central Bank run policies that keep their currencies (Renminbi and Euro) cheap.</p>
<p>Despite significant efforts by President Trump to reduce the U.S. trade deficit, the endeavor did not achieve its intended outcome, as illustrated in <a href="#fig-failbig" class="quarto-xref">Figure&nbsp;<span>5.16</span></a>. One likely reason for this shortfall was the reduction of taxes for large corporations, which enhanced the rate of return on investments. This policy made investing in the U.S. more appealing to foreign investors, potentially counteracting efforts to diminish the trade deficit.</p>
<div id="fig-failbig" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-failbig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.16: The trade deficit of the United States over time
</figcaption>
<div aria-describedby="fig-failbig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="fig/us22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-21" title="Figure&nbsp;5.16: The trade deficit of the United States over time"><img src="fig/us22.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
</figure>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="exr-rooftop" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.13</strong></span> Discuss the pros and cons of Germany’s net export surplus. Please watch this <a href="https://youtu.be/OE-dXYeFmtg">video</a>, see <a href="#fig-roofecon" class="quarto-xref">Figure&nbsp;<span>5.17</span></a>.</p>
<div id="fig-roofecon" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-roofecon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.17: Marcel Fratzscher and Clemens Fuest about Germany’s trade surplus
</figcaption>
<div aria-describedby="fig-roofecon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<iframe width="360" height="215" src="https://www.youtube.com/embed/OE-dXYeFmtg?si=YnalQAYVVJ2g2suW" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen="">
</iframe>
<p>Source: YouTube</p>
</div>
</figure>
</div>
</div>
</div>
</div>
</div>



</section>
</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation column-body">
  <div class="nav-page nav-page-previous">
      <a href="./gdp.html" class="pagination-link" aria-label="Measuring welfare">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Measuring welfare</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./trade.html" class="pagination-link" aria-label="International trade">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">International trade</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>